{"kind":"article","sections":[],"metadata":{"title":"Displaying overlays on a map","role":"sampleCode","platforms":[{"introducedAt":"16.1","beta":false,"name":"iOS"},{"introducedAt":"16.1","beta":false,"name":"iPadOS"},{"introducedAt":"16.0","beta":false,"name":"Xcode"}],"roleHeading":"Sample Code","modules":[{"name":"MapKit"}]},"variants":[{"paths":["/documentation/mapkit/displaying-overlays-on-a-map"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/mapkit/displaying-overlays-on-a-map"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc://com.apple.mapkit/documentation/MapKit/displaying-overlays-on-a-map","interfaceLanguage":"swift"},"seeAlsoSections":[{"identifiers":["doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history"],"title":"Samples","generated":true,"anchor":"Samples"}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mapkit/documentation/MapKit","doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit","doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays"]]},"primaryContentSections":[{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"Overview","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Overlays offer a way to layer content over regions of a map and have that content scale with the map."},{"type":"text","text":" "},{"type":"text","text":"This sample code project demonstrates how to draw common shapes, how to perform custom drawing outside of a common shape, and how to use map tiles from additional data sources."}]},{"text":"Define overlays with geographic coordinates","level":3,"anchor":"Define-overlays-with-geographic-coordinates","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Overlays are data objects that represent geographic information."},{"type":"text","text":" "},{"type":"text","text":"Most overlays use geographic coordinates to create contiguous or noncontiguous sets of lines, rectangles, circles, and other shapes."},{"type":"text","text":" "},{"type":"text","text":"For example, this sample app defines a rectangular area enclosing San Francisco as an array of "},{"type":"text","text":"`CLLocationCoordinate2D`"},{"type":"text","text":" coordinates."}]},{"type":"codeListing","syntax":"swift","code":["/// A rectangular area containing San Francisco.","static let sanFranciscoRectangle = [","    CLLocationCoordinate2D(latitude: 37.816_41, longitude: -122.522_62),","    CLLocationCoordinate2D(latitude: 37.816_41, longitude: -122.355_54),","    CLLocationCoordinate2D(latitude: 37.702_08, longitude: -122.355_54),","    CLLocationCoordinate2D(latitude: 37.702_08, longitude: -122.522_62)","]"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The app creates the overlay objects by providing the coordinate data to an object that conforms to the "},{"type":"reference","overridingTitle":"MKOverlay","overridingTitleInlineContent":[{"type":"codeVoice","code":"MKOverlay"}],"isActive":true,"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlay"},{"type":"text","text":" protocol."},{"type":"text","text":" "},{"type":"text","text":"This data object is responsible for managing the data that defines the overlay."},{"type":"text","text":" "},{"type":"text","text":"MapKit defines several concrete overlay objects for specifying different types of standard shapes, such as circles and polygons."},{"type":"text","text":" "},{"type":"text","text":"The app uses the coordinate array above to create one of these provided overlay objects — a polygon."}]},{"type":"codeListing","syntax":"swift","code":["/// Creates a rectangle polygon.","var rectangleOverlay: MKPolygon {","    return MKPolygon(coordinates: LocationData.sanFranciscoRectangle, count: LocationData.sanFranciscoRectangle.count)","}"]},{"type":"paragraph","inlineContent":[{"text":"Because MapKit defines overlays using a protocol, any class in an app can be an overlay object by conforming to the ","type":"text"},{"code":"MKOverlay","type":"codeVoice"},{"text":" protocol, or by subclassing ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKShape","overridingTitle":"MKShape","overridingTitleInlineContent":[{"type":"codeVoice","code":"MKShape"}],"isActive":true,"type":"reference"},{"text":" or ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMultiPoint","overridingTitle":"MKMultiPoint","overridingTitleInlineContent":[{"code":"MKMultiPoint","type":"codeVoice"}],"isActive":true,"type":"reference"},{"text":". For example, ","type":"text"},{"code":"PeakGroundAccelerationGrid","type":"codeVoice"},{"text":" in this sample app is a custom data class representing an overlay, so it subclasses ","type":"text"},{"code":"MKShape","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"An overlay contains two key properties, a ","type":"text"},{"isActive":true,"overridingTitle":"coordinate","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlay/coordinate","type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"coordinate"}]},{"text":" that defines the center point of the overlay, and the ","type":"text"},{"isActive":true,"overridingTitle":"boundingMapRect","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlay/boundingMapRect","type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"boundingMapRect"}]},{"text":" that the system expresses as an ","type":"text"},{"isActive":true,"overridingTitle":"MKMapRect","identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapRect","type":"reference","overridingTitleInlineContent":[{"code":"MKMapRect","type":"codeVoice"}]},{"text":" that completely encompasses the overlay’s content.","type":"text"},{"text":" ","type":"text"},{"text":"When the app uses system-provided overlay objects, the system automatically computes the values of these properties.","type":"text"},{"text":" ","type":"text"},{"text":"When defining a custom overlay object, the class needs to implement these properties and return appropriate values, as the ","type":"text"},{"type":"codeVoice","code":"PeakGroundAccelerationGrid"},{"text":" class in this app demonstrates.","type":"text"}]},{"text":"Load overlay data using GeoJSON","level":3,"anchor":"Load-overlay-data-using-GeoJSON","type":"heading"},{"type":"paragraph","inlineContent":[{"isActive":true,"type":"reference","identifier":"https://tools.ietf.org/html/rfc7946"},{"type":"text","text":" is a standards-based data format for representing geographic data, and apps often receive overlay data from a server in GeoJSON format."},{"type":"text","text":" "},{"type":"text","text":"Rather than connect to a server, this app uses a local GeoJSON file containing "},{"type":"codeVoice","code":"MultiPolygon"},{"type":"text","text":" features into an "},{"type":"codeVoice","code":"MKMultiPolygon"},{"type":"text","text":" by using "},{"overridingTitle":"MKGeoJSONDecoder","overridingTitleInlineContent":[{"code":"MKGeoJSONDecoder","type":"codeVoice"}],"isActive":true,"type":"reference","identifier":"doc://com.apple.documentation/documentation/MapKit/MKGeoJSONDecoder"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["init() {","    /// In a real app, the event data probably downloads from a server. This sample loads GeoJSON data from a local file instead.","    if let jsonUrl = Bundle.main.url(forResource: \"event\", withExtension: \"json\") {","        do {","            let eventData = try Data(contentsOf: jsonUrl)","","            // Use the `MKGeoJSONDecoder` to convert the JSON data into MapKit objects, such as `MKGeoJSONFeature`.","            let decoder = MKGeoJSONDecoder()","            let jsonObjects = try decoder.decode(eventData)","","            parse(jsonObjects)","        } catch {","            print(\"Error decoding GeoJSON: \\(error).\")","        }","    }","}","","private func parse(_ jsonObjects: [MKGeoJSONObject]) {","    for object in jsonObjects {","","        /**","         In this sample's GeoJSON data, there are only GeoJSON features at the top level, so this parse method only checks for those. An","         implementation that parses arbitrary GeoJSON files needs to check for GeoJSON geometry objects too.","        */","        if let feature = object as? MKGeoJSONFeature {","            for geometry in feature.geometry {","","                /**","                 Separate annotation objects from overlay objects because you add them to the map view in different ways. This sample","                 GeoJSON only contains `Point` and `MultiPolygon` geometry. In a generic parser, check for all possible geometry types.","                */","                if let multiPolygon = geometry as? MKMultiPolygon {","                    overlays.append(multiPolygon)","                } else if let point = geometry as? MKPointAnnotation {","                     // The name of the annotation passes in the feature properties.","                     // Parse the name and apply it to the annotation.","                    configure(annotation: point, using: feature.properties)","                    annotations.append(point)","                }","            }","        }","    }","}"]},{"text":"Display overlays on a map view","level":3,"anchor":"Display-overlays-on-a-map-view","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The app adds the overlay data objects to the map in a specific order to ensure that certain overlays display on top of others."},{"type":"text","text":" "},{"type":"text","text":"To specify whether an overlay is above or below content that the map provides, such as roads and labels, the app calls "},{"overridingTitleInlineContent":[{"code":"addOverlay(_:level:)","type":"codeVoice"}],"type":"reference","overridingTitle":"addOverlay(_:level:)","identifier":"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452635-addoverlay","isActive":true},{"type":"text","text":" with the "},{"type":"codeVoice","code":"level"},{"type":"text","text":" parameter as a value that "},{"overridingTitleInlineContent":[{"code":"MKOverlayLevel","type":"codeVoice"}],"type":"reference","overridingTitle":"MKOverlayLevel","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayLevel","isActive":true},{"type":"text","text":" provides."}]},{"type":"codeListing","syntax":"swift","code":["mapView.addOverlay(reliefTileOverlay, level: .aboveLabels)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The overlay data object doesn’t draw the overlay on the map."},{"type":"text","text":" "},{"type":"text","text":"A second object, called an "},{"type":"emphasis","inlineContent":[{"type":"text","text":"overlay renderer"}]},{"type":"text","text":", handles the drawing responsibilities for displaying the overlay on the map view."},{"type":"text","text":" "},{"type":"text","text":"After adding an overlay, the map view calls "},{"type":"reference","overridingTitle":"mapView(_:rendererFor:)","overridingTitleInlineContent":[{"type":"codeVoice","code":"mapView(_:rendererFor:)"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapViewDelegate/mapView(_:rendererFor:)","isActive":true},{"type":"text","text":" on its delegate to create an appropriate renderer object."},{"type":"text","text":" "},{"type":"text","text":"Because this app demonstrates many different overlays, its implementation of "},{"type":"codeVoice","code":"mapView(_:rendererFor:)"},{"type":"text","text":" creates many different types of overlay renderers."},{"type":"text","text":" "},{"type":"text","text":"Most apps only use a small number of overlay types, so this function only needs to create the small number of corresponding overlay renderer types."}]},{"type":"codeListing","syntax":"swift","code":["func mapView(_ mapView: MKMapView, rendererFor overlay: MKOverlay) -> MKOverlayRenderer {","    switch overlay {","    case let overlay as MKCircle:","        return createCircleRenderer(for: overlay)","    case let overlay as MKGeodesicPolyline:","        return createGeodesicPolylineRenderer(for: overlay)","    case let overlay as MKPolyline where currentExample == .gradientPolyline:","        return createGradientPolylineRenderer(for: overlay)","    case let overlay as MKPolyline:","        return createPolylineRenderer(for: overlay)","    case let overlay as MKPolygon where currentExample == .blendModes:","        return createBlendModesPolygonRenderer(for: overlay)","    case let overlay as MKPolygon:","        return createPolygonRenderer(for: overlay)","    case let overlay as MKMultiPolygon:","        return createMultiPolylineRenderer(for: overlay)","    case let overlay as PeakGroundAccelerationGrid:","        return createCustomRenderer(for: overlay)","    case let overlay as MKTileOverlay:","        return createTileRenderer(for: overlay)","    default:","        return MKOverlayRenderer(overlay: overlay)","    }","}"]},{"type":"paragraph","inlineContent":[{"text":"After the app creates the renderer and returns it from ","type":"text"},{"code":"mapView(_:rendererFor:)","type":"codeVoice"},{"text":", the map view uses the ","type":"text"},{"code":"boundingMapRect","type":"codeVoice"},{"text":" property on the overlay data object to determine when the returned overlay renderer draws the overlay on the map.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"code":"overlays","type":"codeVoice"}],"identifier":"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452784-overlays","overridingTitle":"overlays"},{"type":"text","text":" property of "},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"MKMapView"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapView","overridingTitle":"MKMapView"},{"type":"text","text":" stores the registered overlays, but the order of the array doesn’t necessarily reflect their visual order on the map."},{"type":"text","text":" "},{"type":"text","text":"To understand the rendering order of overlays at a specific level, see "},{"isActive":true,"type":"reference","overridingTitleInlineContent":[{"code":"overlays(in:)","type":"codeVoice"}],"identifier":"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452757-overlays","overridingTitle":"overlays(in:)"},{"type":"text","text":"."}]},{"text":"Use the standard overlay objects for common shapes","level":3,"anchor":"Use-the-standard-overlay-objects-for-common-shapes","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The app highlights specific map regions with basic shapes by using the standard overlay classes, including "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"MKCircle"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKCircle","isActive":true,"type":"reference","overridingTitle":"MKCircle"},{"type":"text","text":", "},{"overridingTitleInlineContent":[{"code":"MKPolyline","type":"codeVoice"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolyline","isActive":true,"type":"reference","overridingTitle":"MKPolyline"},{"type":"text","text":", and "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"MKPolygon"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolygon","isActive":true,"type":"reference","overridingTitle":"MKPolygon"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"For example, it creates a circle overlay using "},{"type":"codeVoice","code":"MKCircle"},{"type":"text","text":" with a center coordinate and a radius specified in meters to highlight San Francisco."}]},{"type":"codeListing","syntax":"swift","code":["/// Create a circle overlay that centers on San Francisco.","let circleOverlay = MKCircle(center: LocationData.sanFranciscoGeographicCenter, radius: 9000)","mapView.addOverlay(circleOverlay, level: overlayLevel)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The standard overlay classes define the basic shape of the overlay, and the app uses them in conjunction with the "},{"type":"reference","overridingTitle":"MKCircleRenderer","identifier":"doc://com.apple.documentation/documentation/MapKit/MKCircleRenderer","overridingTitleInlineContent":[{"type":"codeVoice","code":"MKCircleRenderer"}],"isActive":true},{"type":"text","text":", "},{"type":"reference","overridingTitle":"MKPolylineRenderer","identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolylineRenderer","overridingTitleInlineContent":[{"code":"MKPolylineRenderer","type":"codeVoice"}],"isActive":true},{"type":"text","text":", or "},{"type":"reference","overridingTitle":"MKPolygonRenderer","identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolygonRenderer","overridingTitleInlineContent":[{"code":"MKPolygonRenderer","type":"codeVoice"}],"isActive":true},{"type":"text","text":" classes to handle the rendering of that shape on the map."},{"type":"text","text":" "},{"type":"text","text":"The app creates a renderer for the circle described above with the following code:"}]},{"type":"codeListing","syntax":"swift","code":["func createCircleRenderer(for circle: MKCircle) -> MKCircleRenderer {","    /**","     Some of the most common customizations for an `MKOverlayRenderer` include customizing drawing settings, such as the","     fill color of an enclosed shape, or the stroke color for the edge of the shape.","     */","    let renderer = MKCircleRenderer(circle: circle)","    renderer.lineWidth = 2","    renderer.strokeColor = .systemBlue","    renderer.fillColor = .systemTeal","    renderer.alpha = 0.5","    ","    return renderer","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the app uses the provided renderer classes for common shapes, MapKit vectorizes overlay shapes so that they always remain sharp while the map scales."},{"type":"text","text":" "},{"type":"text","text":"The app doesn’t change the default value of the "},{"type":"reference","overridingTitleInlineContent":[{"code":"shouldRasterize","type":"codeVoice"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayPathRenderer/shouldRasterize","overridingTitle":"shouldRasterize","isActive":true},{"type":"text","text":" property, so the standard overlay shapes always remain sharp."},{"type":"text","text":" "},{"type":"text","text":"Subclassing any of the provided renderer objects and providing a custom implementation of "},{"type":"reference","overridingTitleInlineContent":[{"code":"draw(_:zoomScale:in:)","type":"codeVoice"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/draw(_:zoomScale:in:)","overridingTitle":"draw(_:zoomScale:in:)","isActive":true},{"type":"text","text":", like the "},{"type":"codeVoice","code":"PeakGroundAccelerationOverlayRenderer"},{"type":"text","text":" class, automatically enables rasterized rendering."}]},{"text":"Set drawing properties to customize the overlay rendering","level":3,"anchor":"Set-drawing-properties-to-customize-the-overlay-rendering","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The standard overlay renderers allow customization of common drawing properties for the fill and edges.","type":"text"},{"text":" ","type":"text"},{"text":"For example, the app displays an ","type":"text"},{"type":"codeVoice","code":"MKPolyline"},{"text":" overlay using dashes instead of a solid line, and sets a customized dash pattern using the ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern","type":"reference","overridingTitleInlineContent":[{"code":"lineDashPattern","type":"codeVoice"}],"overridingTitle":"lineDashPattern"},{"text":" property of an ","type":"text"},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolylineRenderer","type":"reference","overridingTitleInlineContent":[{"code":"MKPolylineRenderer","type":"codeVoice"}],"overridingTitle":"MKPolylineRenderer"},{"text":".","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["/**"," Apply a custom pattern to the line, alternating dash length with space length in drawing points."," The pattern repeats for the length of the polyline."," */","renderer.lineDashPattern = [20 as NSNumber,   // Long dash","                            10 as NSNumber,   // Space","                             5 as NSNumber,   // Shorter dash","                            10 as NSNumber,   // Space","                             1 as NSNumber,   // Dot","                            10 as NSNumber]   // Space"]},{"type":"paragraph","inlineContent":[{"text":"MapKit also provides ","type":"text"},{"overridingTitle":"MKGradientPolylineRenderer","identifier":"doc://com.apple.documentation/documentation/MapKit/MKGradientPolylineRenderer","type":"reference","isActive":true,"overridingTitleInlineContent":[{"code":"MKGradientPolylineRenderer","type":"codeVoice"}]},{"text":" to draw a polyline with a color gradient.","type":"text"},{"text":" ","type":"text"},{"text":"The app configures a gradient renderer in the following way:","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func createGradientPolylineRenderer(for line: MKPolyline) -> MKGradientPolylineRenderer {","    let renderer = MKGradientPolylineRenderer(polyline: line)","    ","    let colorPalette: [UIColor] = [.systemPurple, .systemMint, .systemOrange, .systemTeal, .systemRed]","    ","    /**","     Gradient polylines take an array of colors and an array of locations to place each color within the gradient.","     The system describes the location values as a fractional distance along the polyline between 0.0 (representing the first point) and","     1.0 (representing the last point).","     ","     For apps that add a color to the gradient per point in the polyline, `MKPolyline` offers the `location(atPointIndex:)` function to","     compute the location value for use with the gradient polyline.","     */","    var unitDistances = [CGFloat]()","    var colors = [UIColor]()","    var index = 0","    while index < line.pointCount {","        // Figure out the location of a point in the polyline as a fraction of unit distance between 0 and 1.","        unitDistances.append(line.location(atPointIndex: index))","        ","        // Pick a color to add to the gradient.","        colors.append(colorPalette[index % colorPalette.count])","        ","        index += 1","    }","    ","    renderer.setColors(colors, locations: unitDistances)","    renderer.lineWidth = 2","    ","    return renderer","}"]},{"text":"Render multiple overlays with the same style efficiently","level":3,"anchor":"Render-multiple-overlays-with-the-same-style-efficiently","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"It’s common to have multiple related overlays appear on the map with an identical visual style."},{"type":"text","text":" "},{"type":"text","text":"For example, the app displays a map of an outdoor event that uses multiple overlays to show where the stage is located in relation to different event booths."},{"type":"text","text":" "},{"type":"text","text":"Because the app shows each of these overlays using the same color scheme, it groups the individual overlay objects together using an "},{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMultiPolygon","type":"reference","overridingTitleInlineContent":[{"code":"MKMultiPolygon","type":"codeVoice"}],"isActive":true,"overridingTitle":"MKMultiPolygon"},{"type":"text","text":" object."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The app then adds the grouped overlay to the map view, rather than adding the individual overlays, to avoid requesting a separate renderer for each overlay from its delegate."},{"type":"text","text":" "},{"type":"text","text":"Instead, the app returns an "},{"isActive":true,"overridingTitleInlineContent":[{"code":"MKMultiPolygonRenderer","type":"codeVoice"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMultiPolygonRenderer","type":"reference","overridingTitle":"MKMultiPolygonRenderer"},{"type":"text","text":" from the delegate."},{"type":"text","text":" "},{"type":"text","text":"This returned renderer applies the same drawing properties to all overlays within the  "},{"code":"MKMultiPolygon","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This is more efficient than creating a renderer for each overlay."}]},{"type":"codeListing","syntax":"swift","code":["func createMultiPolylineRenderer(for multiPolygon: MKMultiPolygon) -> MKMultiPolygonRenderer {","    let renderer = MKMultiPolygonRenderer(multiPolygon: multiPolygon)","    renderer.fillColor = UIColor(named: \"MultiPolygonOverlayFill\")","    renderer.strokeColor = UIColor(named: \"MultiPolygonOverlayStroke\")","    renderer.lineWidth = 2.0","","    return renderer","}"]},{"type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"To maximize rendering efficiency, developers need to group overlays using "},{"type":"codeVoice","code":"MKMultiPolyline"},{"type":"text","text":" or "},{"type":"codeVoice","code":"MKMultiPolygon"},{"type":"text","text":" whenever the visual style is the same."},{"type":"text","text":" "},{"type":"text","text":"This is especially important when an app displays significant numbers of visually identical overlays."}],"type":"paragraph"}],"style":"note"},{"text":"Create visual effects using blend modes","level":3,"anchor":"Create-visual-effects-using-blend-modes","type":"heading"},{"type":"paragraph","inlineContent":[{"inlineContent":[{"type":"text","text":"Blend modes"}],"type":"emphasis"},{"text":" relate the content that draws in an overlay to the content that draws behind the overlay.","type":"text"},{"text":" ","type":"text"},{"text":"This enables creating visual effects on the map by adding overlays with a specific Z-order and applying a blend mode on the different overlays.","type":"text"},{"text":" ","type":"text"},{"text":"For example, the app highlights a park hosting an outdoor event by using blend modes to lighten the map areas outside the park and to amplify the colors within the park.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To create such an effect, the app uses two overlays."},{"type":"text","text":" "},{"type":"text","text":"The first overlay covers the entire map except for an inner polygon for the park, and the second overlay is a polygon outlining only the park."}]},{"type":"codeListing","syntax":"swift","code":["/// Turn an array of points into a polygon. You can also load the polygon from a GeoJSON file by using `MKGeoJSONDecoder`.","let parkPolygon = MKPolygon(coordinates: LocationData.plazaDeCesarChavezParkOutline,","                                 count: LocationData.plazaDeCesarChavezParkOutline.count)","","/// Create an overlay polygon that covers the entire world, except for a cutout of the highlighted park.","let worldPoints = [MKMapRect.world.origin,","                   MKMapPoint(x: MKMapRect.world.origin.x, y: MKMapRect.world.origin.y + MKMapRect.world.size.height),","                   MKMapPoint(x: MKMapRect.world.origin.x + MKMapRect.world.size.width, y: MKMapRect.world.origin.y),","                   MKMapPoint(x: MKMapRect.world.origin.x + MKMapRect.world.size.width,","                              y: MKMapRect.world.origin.y + MKMapRect.world.size.height)]","let desaturatedBase = MKPolygon(points: worldPoints, count: worldPoints.count, interiorPolygons: [parkPolygon])"]},{"type":"paragraph","inlineContent":[{"text":"When the map view requests renderer objects from the map delegate for these overlay objects, the app configures the ","type":"text"},{"overridingTitleInlineContent":[{"code":"blendMode","type":"codeVoice"}],"type":"reference","isActive":true,"overridingTitle":"blendMode","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/blendMode"},{"text":" property with the ","type":"text"},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"screen"}],"type":"reference","isActive":true,"overridingTitle":"screen","identifier":"doc://com.apple.documentation/documentation/CoreGraphics/CGBlendMode/screen"},{"text":" blend mode to lighten the map area outside the park, and the ","type":"text"},{"overridingTitleInlineContent":[{"code":"colorBurn","type":"codeVoice"}],"type":"reference","isActive":true,"overridingTitle":"colorBurn","identifier":"doc://com.apple.documentation/documentation/CoreGraphics/CGBlendMode/colorBurn"},{"text":" blend mode to darken the colors within the park.","type":"text"}]},{"type":"codeListing","syntax":"swift","code":["func createBlendModesPolygonRenderer(for overlay: MKPolygon) -> MKPolygonRenderer {","    let renderer = MKPolygonRenderer(polygon: overlay)","    ","    if overlay.interiorPolygons == nil {","        /// An overlay without `interiorPolygons` is the overlay highlighting the park.","        renderer.fillColor = traitCollection.userInterfaceStyle == .light ? .darkGray : .white","        renderer.blendMode = .colorBurn","    } else {","        /// An overlay with `interiorPolygons` is the background overlay to desaturate.","        renderer.fillColor = .gray","        renderer.blendMode = .screen","    }","    return renderer","}"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"For further information on blend modes, see “Setting Blend Modes” and “Using Blend Modes with Images” in "},{"type":"reference","identifier":"https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066","isActive":true},{"type":"text","text":"."}]},{"text":"Define a custom overlay renderer","level":3,"anchor":"Define-a-custom-overlay-renderer","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To draw complex overlays that go beyond drawing boundaries and filling standard overlay shapes, this sample code project creates a custom overlay renderer."},{"type":"text","text":" "},{"type":"text","text":"The app contains data related to earthquake hazards, and defines a custom "},{"type":"codeVoice","code":"MKOverlay"},{"type":"text","text":" to represent that hazard data. It also defines a custom overlay renderer to draw a color-coded, shaded map of hazards based on the data."}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"To create a custom overlay renderer, the app subclasses "},{"code":"MKOverlayRenderer","type":"codeVoice"},{"type":"text","text":" and implements "},{"code":"draw(_:zoomScale:in:)","type":"codeVoice"},{"type":"text","text":" to draw the earthquake data into the provided "},{"identifier":"doc://com.apple.documentation/documentation/CoreGraphics/CGContext","overridingTitle":"CGContext","overridingTitleInlineContent":[{"type":"codeVoice","code":"CGContext"}],"isActive":true,"type":"reference"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"MapKit calls this method concurrently on multiple background queues for the app to draw the overlay, with each call rendering a specific section of the overlay within the bounds of the "},{"code":"mapRect","type":"codeVoice"},{"type":"text","text":" parameter."}]},{"type":"codeListing","syntax":"swift","code":["override func draw(_ mapRect: MKMapRect, zoomScale: MKZoomScale, in context: CGContext) {","    // Don't draw anything that doesn't intersect the data set.","    guard mapRect.intersects(data.boundingMapRect) else { return }","    ","    /**","     Determine the section of the overlay to render. MapKit breaks overlays into multiple rectangles for rendering on multiple threads.","     Each call to `draw(_:zoomScale:in:)` should only render within bounds of the provided `mapRect`.","     If your drawing implementation needs to draw content outside of the provided `mapRect` as part of its drawing algorithm, apply a clipping","     rectangle by calling `clip(to:)` on the `CGContext`.","     */","    let intersection = mapRect.intersection(data.boundingMapRect)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the app draws the custom overlay, it uses "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapPoint","type":"reference","overridingTitleInlineContent":[{"type":"codeVoice","code":"MKMapPoint"}],"overridingTitle":"MKMapPoint"},{"type":"text","text":" data associated with the overlay to define shapes."},{"type":"text","text":" "},{"type":"text","text":"When it needs to convert data between MapKit geometry and Core Graphics geometry, it uses "},{"isActive":true,"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/point(for:)","type":"reference","overridingTitleInlineContent":[{"code":"point(for:)","type":"codeVoice"}],"overridingTitle":"point(for:)"},{"type":"text","text":"."}]},{"type":"codeListing","syntax":"swift","code":["let point1Conversion = point(for: coord1.mapPoint)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"MapKit also provides "},{"overridingTitleInlineContent":[{"type":"codeVoice","code":"mapRect(for:)"}],"type":"reference","isActive":true,"overridingTitle":"mapRect(for:)","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/mapRect(for:)"},{"type":"text","text":" for converting rectangles between MapKit geometry and Core Graphics geometry."},{"type":"text","text":" "},{"type":"text","text":"When implementing a custom renderer, the app doesn’t use the "},{"code":"bounds","type":"codeVoice"},{"type":"text","text":" or "},{"code":"frame","type":"codeVoice"},{"type":"text","text":" of the "},{"code":"MKMapView","type":"codeVoice"},{"type":"text","text":" as reference points during drawing."}]},{"text":"Load custom map tiles","level":3,"anchor":"Load-custom-map-tiles","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"MapKit supports using custom bitmap map tiles to provide an underlying map that’s customizable."},{"type":"text","text":" "},{"type":"text","text":"For example, this app displays map tiles that emphasize rivers and mountains."}]},{"type":"paragraph","inlineContent":[{"text":"To use a custom bitmap map tile overlay, the app uses ","type":"text"},{"isActive":true,"overridingTitleInlineContent":[{"type":"codeVoice","code":"MKTileOverlay"}],"type":"reference","identifier":"doc://com.apple.documentation/documentation/MapKit/MKTileOverlay","overridingTitle":"MKTileOverlay"},{"text":" to manage loading the tile data and ","type":"text"},{"isActive":true,"overridingTitleInlineContent":[{"type":"codeVoice","code":"MKTileOverlayRenderer"}],"type":"reference","identifier":"doc://com.apple.documentation/documentation/MapKit/MKTileOverlayRenderer","overridingTitle":"MKTileOverlayRenderer"},{"text":" to render the map tiles.","type":"text"},{"text":" ","type":"text"},{"text":"When creating the tile overlay, the app provides a URL template with placeholder values for the tile position, zoom level, and scale factor to the ","type":"text"},{"type":"codeVoice","code":"MKTileOverlay"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"When the tile overlay loads the data, MapKit replaces the placeholder values with the required values to load tiles for a specific map region according to the EPSG:3857 spherical Mercator projection coordinate system.","type":"text"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL template can be either an HTTP URL or a file URL, and this app uses both."},{"type":"text","text":" "},{"type":"text","text":"For example, it loads some map tiles bundled with the app and specifies a file URL template that locates the map tiles within the app’s bundle."}]},{"type":"codeListing","syntax":"swift","code":["let tileDirectoryName = \"tileData\"","guard let resourcePath = Bundle.main.resourcePath else { return }","let localPath = \"file://\\(resourcePath)/\\(tileDirectoryName)/{z}/{x}/{y}.jpg\"","let tileOverlay = MKTileOverlay(urlTemplate: localPath)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"When the app loads tiles from a server, it also does so with a URL template, replacing the file URL with an HTTP URL."}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"CustomLoadingTileOverlay","type":"codeVoice"},{"text":" class in this sample code project implements ","type":"text"},{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKTileOverlay/loadTile(at:result:)","overridingTitleInlineContent":[{"code":"loadTile(at:result:)","type":"codeVoice"}],"isActive":true,"overridingTitle":"loadTile(at:result:)","type":"reference"},{"text":" to show how to customize tile-loading behavior for specialized loading needs.","type":"text"}]},{"text":"Use an overlay as an annotation","level":3,"anchor":"Use-an-overlay-as-an-annotation","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The "},{"code":"MKOverlay","type":"codeVoice"},{"type":"text","text":" protocol conforms to the "},{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKAnnotation","isActive":true,"overridingTitle":"MKAnnotation","type":"reference","overridingTitleInlineContent":[{"code":"MKAnnotation","type":"codeVoice"}]},{"type":"text","text":" protocol."},{"type":"text","text":" "},{"type":"text","text":"As a result, all overlay objects are also annotation objects."},{"type":"text","text":" "},{"type":"text","text":"When adding an overlay as an annotation to the map, "},{"code":"MKMapView","type":"codeVoice"},{"type":"text","text":" displays it at the overlay’s "},{"code":"coordinate","type":"codeVoice"},{"type":"text","text":" property."},{"type":"text","text":" "},{"type":"text","text":"For example, the app uses a polygon outlining the park for an outdoor concert as an annotation to label the concert location."}]},{"type":"codeListing","syntax":"swift","code":["/**"," Types that derive from `MKOverlay`, such as `MKPolygon`, also conform to `MKAnnotation`, enabling you to add them to the map as an overlay,"," as well as place an annotation on the overlay to label it."," */","parkPolygon.title = \"Concert Location\"","mapView.addAnnotation(parkPolygon)"]},{"type":"paragraph","inlineContent":[{"type":"text","text":"Because the app treats the overlay object as both an overlay and an annotation, it’s responsible for adding and removing the object from the map view as both an annotation and as an overlay."}]}]}],"sampleCodeDownload":{"kind":"sampleDownload","action":{"type":"reference","isActive":true,"identifier":"f14a9bc447c5/DisplayingOverlaysOnAMap.zip","overridingTitle":"Download"}},"abstract":[{"type":"text","text":"Add regions of layered content to a map view."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452635-addoverlay":{"identifier":"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452635-addoverlay","abstract":[{"text":"Adds the overlay object to the map at the specified level.","type":"text"}],"kind":"symbol","title":"addOverlay(_:level:)","url":"/documentation/mapkit/mkmapview/1452635-addoverlay","type":"topic","fragments":[{"text":"func ","kind":"text"},{"text":"addOverlay","kind":"identifier"},{"text":"(any MKOverlay, ","kind":"text"},{"text":"level","kind":"identifier"},{"text":": MKOverlayLevel)","kind":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/MapKit/MKGradientPolylineRenderer":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKGradientPolylineRenderer","abstract":[{"text":"A visual representation of any polyline overlay object with a gradient.","type":"text"}],"kind":"symbol","title":"MKGradientPolylineRenderer","url":"/documentation/MapKit/MKGradientPolylineRenderer","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKGradientPolylineRenderer","kind":"identifier"}],"role":"symbol"},"doc://com.apple.documentation/documentation/MapKit/MKMultiPolygonRenderer":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMultiPolygonRenderer","abstract":[{"text":"The visual representation of multiple polygon overlays.","type":"text"}],"kind":"symbol","title":"MKMultiPolygonRenderer","url":"/documentation/MapKit/MKMultiPolygonRenderer","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMultiPolygonRenderer","kind":"identifier"}],"role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit":{"role":"collection","kind":"symbol","type":"topic","title":"MapKit","abstract":[{"text":"Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.","type":"text"}],"url":"/documentation/mapkit","identifier":"doc://com.apple.mapkit/documentation/MapKit"},"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452757-overlays":{"identifier":"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452757-overlays","url":"/documentation/mapkit/mkmapview/1452757-overlays","abstract":[{"text":"Returns overlay objects in the specified level of the map.","type":"text"}],"fragments":[{"text":"func ","kind":"text"},{"text":"overlays","kind":"identifier"},{"text":"(","kind":"text"},{"text":"in","kind":"identifier"},{"text":": MKOverlayLevel) -> [any MKOverlay]","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"overlays(in:)"},"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/draw(_:zoomScale:in:)":{"type":"topic","title":"draw(_:zoomScale:in:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mapRect","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"zoomScale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MKZoomScale","preciseIdentifier":"c:@T@MKZoomScale","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGContext","preciseIdentifier":"c:@T@CGContextRef","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Draws the overlay’s contents at the specified location on the map.","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/draw(_:zoomScale:in:)","url":"/documentation/MapKit/MKOverlayRenderer/draw(_:zoomScale:in:)","role":"symbol","kind":"symbol"},"f14a9bc447c5/DisplayingOverlaysOnAMap.zip":{"identifier":"f14a9bc447c5/DisplayingOverlaysOnAMap.zip","checksum":"f14a9bc447c57e9400a124c1a112aa02895f44cb08a5fafe898a5f3b6cba0ffde7d8befb2210d9c8c17a6e766f24a6e49892898a60d5a9895d03372097547e26","url":"https://docs-assets.developer.apple.com/published/f14a9bc447c5/DisplayingOverlaysOnAMap.zip","type":"download"},"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/blendMode":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/blendMode","url":"/documentation/MapKit/MKOverlayRenderer/blendMode","abstract":[{"text":"The blend mode to apply to the overlay.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"blendMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@CGBlendMode","text":"CGBlendMode","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","title":"blendMode"},"doc://com.apple.documentation/documentation/MapKit/MKPolygon":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolygon","url":"/documentation/MapKit/MKPolygon","abstract":[{"text":"A closed polygon overlay.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKPolygon","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"MKPolygon"},"doc://com.apple.documentation/documentation/MapKit/MKShape":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKShape","url":"/documentation/MapKit/MKShape","abstract":[{"text":"An abstract class that defines the basic properties for all shape-based overlay objects.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKShape","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"MKShape"},"doc://com.apple.documentation/documentation/MapKit/MKCircleRenderer":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKCircleRenderer","url":"/documentation/MapKit/MKCircleRenderer","abstract":[{"text":"The visual representation of a circular overlay.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKCircleRenderer","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"MKCircleRenderer"},"doc://com.apple.documentation/documentation/MapKit/MKMultiPoint":{"url":"/documentation/MapKit/MKMultiPoint","kind":"symbol","title":"MKMultiPoint","abstract":[{"text":"An abstract class that defines the common behavior that open and closed polygon overlays share.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMultiPoint","kind":"identifier"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMultiPoint","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/MapKit/MKMapRect":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapRect","title":"MKMapRect","type":"topic","abstract":[{"type":"text","text":"A rectangular area on a two-dimensional map projection."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MKMapRect"}],"url":"/documentation/MapKit/MKMapRect","kind":"symbol"},"doc://com.apple.documentation/documentation/CoreGraphics/CGBlendMode/colorBurn":{"url":"/documentation/CoreGraphics/CGBlendMode/colorBurn","kind":"symbol","title":"CGBlendMode.colorBurn","abstract":[{"text":"Darkens the background image samples to reflect the source image samples. Source image sample values that specify white do not produce a change.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorBurn","kind":"identifier"}],"identifier":"doc://com.apple.documentation/documentation/CoreGraphics/CGBlendMode/colorBurn","role":"symbol","type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit":{"url":"/documentation/mapkit/mapkit-for-appkit-and-uikit","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit","kind":"article","title":"MapKit for AppKit and UIKit"},"doc://com.apple.documentation/documentation/MapKit/MKCircle":{"url":"/documentation/MapKit/MKCircle","kind":"symbol","title":"MKCircle","abstract":[{"text":"A circular overlay with a configurable radius that you center on a geographic coordinate.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKCircle","kind":"identifier"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKCircle","role":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/MapKit/MKMultiPolygon":{"abstract":[{"text":"A collection of multiple closed polygon overlays.","type":"text"}],"role":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKMultiPolygon","type":"topic","url":"/documentation/MapKit/MKMultiPolygon","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMultiPolygon","kind":"identifier"}],"title":"MKMultiPolygon","kind":"symbol"},"doc://com.apple.documentation/documentation/MapKit/MKTileOverlay/loadTile(at:result:)":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKTileOverlay/loadTile(at:result:)","kind":"symbol","type":"topic","url":"/documentation/MapKit/MKTileOverlay/loadTile(at:result:)","title":"loadTile(at:result:)","abstract":[{"text":"Loads the specified tile asynchronously.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadTile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MKTileOverlayPath","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKTileOverlayPath"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping ","kind":"attribute"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, (any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.apple.documentation/documentation/MapKit/MKPolylineRenderer":{"identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolylineRenderer","kind":"symbol","type":"topic","url":"/documentation/MapKit/MKPolylineRenderer","title":"MKPolylineRenderer","abstract":[{"text":"A visual representation of any polyline overlay object.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKPolylineRenderer","kind":"identifier"}],"role":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"title":"Technologies","kind":"technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies"},"doc://com.apple.documentation/documentation/CoreGraphics/CGBlendMode/screen":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/CoreGraphics/CGBlendMode/screen","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"screen","kind":"identifier"}],"abstract":[{"text":"Multiplies the inverse of the source image samples with the inverse of the background image samples, resulting in colors that are at least as light as either of the two contributing sample colors.","type":"text"}],"title":"CGBlendMode.screen","url":"/documentation/CoreGraphics/CGBlendMode/screen","kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/CoreGraphics/CGContext":{"abstract":[{"type":"text","text":"A Quartz 2D drawing environment."}],"role":"symbol","type":"topic","url":"/documentation/CoreGraphics/CGContext","identifier":"doc://com.apple.documentation/documentation/CoreGraphics/CGContext","title":"CGContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGContext"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/mapRect(for:)":{"role":"symbol","title":"mapRect(for:)","url":"/documentation/MapKit/MKOverlayRenderer/mapRect(for:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapRect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"rect","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect","kind":"typeIdentifier"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/mapRect(for:)","type":"topic","abstract":[{"text":"Returns the rectangle on the map that corresponds to the specified rectangle in the overlay renderer’s drawing area.","type":"text"}]},"doc://com.apple.documentation/documentation/MapKit/MKPolygonRenderer":{"role":"symbol","title":"MKPolygonRenderer","url":"/documentation/MapKit/MKPolygonRenderer","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKPolygonRenderer","kind":"identifier"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolygonRenderer","type":"topic","abstract":[{"text":"The visual representation of a single polygon overlay.","type":"text"}]},"https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066":{"identifier":"https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066","title":"Quartz 2D Programming Guide","url":"https://developer.apple.com/library/archive/documentation/GraphicsImaging/Conceptual/drawingwithquartz2d/Introduction/Introduction.html#//apple_ref/doc/uid/TP30001066","titleInlineContent":[{"text":"Quartz 2D Programming Guide","type":"text"}],"type":"link"},"doc://com.apple.documentation/documentation/MapKit/MKTileOverlay":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKTileOverlay","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKTileOverlay","kind":"identifier"}],"abstract":[{"text":"An overlay that covers an area of the map with tiles of bitmap images.","type":"text"}],"title":"MKTileOverlay","url":"/documentation/MapKit/MKTileOverlay","kind":"symbol","type":"topic"},"https://tools.ietf.org/html/rfc7946":{"identifier":"https://tools.ietf.org/html/rfc7946","title":"GeoJSON","url":"https://tools.ietf.org/html/rfc7946","titleInlineContent":[{"text":"GeoJSON","type":"text"}],"type":"link"},"doc://com.apple.documentation/documentation/MapKit/MKOverlayLevel":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayLevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKOverlayLevel","kind":"identifier"}],"abstract":[{"text":"Constants that indicate the position of overlays relative to other content.","type":"text"}],"title":"MKOverlayLevel","url":"/documentation/MapKit/MKOverlayLevel","kind":"symbol","type":"topic"},"doc://com.apple.documentation/documentation/MapKit/MKGeoJSONDecoder":{"title":"MKGeoJSONDecoder","url":"/documentation/MapKit/MKGeoJSONDecoder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKGeoJSONDecoder","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKGeoJSONDecoder","abstract":[{"text":"An object that decodes GeoJSON objects into MapKit types.","type":"text"}],"type":"topic"},"doc://com.apple.documentation/documentation/MapKit/MKTileOverlayRenderer":{"title":"MKTileOverlayRenderer","url":"/documentation/MapKit/MKTileOverlayRenderer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKTileOverlayRenderer","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKTileOverlayRenderer","abstract":[{"text":"The renderer for a tile overlay that handles the drawing of bitmap images on the map surface.","type":"text"}],"type":"topic"},"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452784-overlays":{"role":"symbol","kind":"symbol","url":"/documentation/mapkit/mkmapview/1452784-overlays","type":"topic","title":"overlays","identifier":"doc://com.apple.documentation/documentation/mapkit/mkmapview/1452784-overlays","abstract":[{"text":"The overlay objects associated with the map view.","type":"text"}],"fragments":[{"kind":"text","text":"var "},{"kind":"identifier","text":"overlays"},{"kind":"text","text":": [any MKOverlay]"}]},"doc://com.apple.documentation/documentation/MapKit/MKAnnotation":{"role":"symbol","kind":"symbol","url":"/documentation/MapKit/MKAnnotation","type":"topic","title":"MKAnnotation","identifier":"doc://com.apple.documentation/documentation/MapKit/MKAnnotation","abstract":[{"text":"An interface for associating your content with a specific map location.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"MKAnnotation","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}]},"doc://com.apple.documentation/documentation/MapKit/MKOverlay/coordinate":{"type":"topic","role":"symbol","title":"coordinate","url":"/documentation/MapKit/MKOverlay/coordinate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"coordinate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CLLocationCoordinate2D","text":"CLLocationCoordinate2D","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlay/coordinate","abstract":[{"text":"The approximate center point of the overlay area.","type":"text"}]},"doc://com.apple.documentation/documentation/MapKit/MKPolyline":{"abstract":[{"text":"An open polygon overlay consisting of one or more connected line segments.","type":"text"}],"role":"symbol","type":"topic","url":"/documentation/MapKit/MKPolyline","identifier":"doc://com.apple.documentation/documentation/MapKit/MKPolyline","title":"MKPolyline","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MKPolyline"}],"kind":"symbol"},"doc://com.apple.documentation/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern":{"role":"symbol","kind":"symbol","url":"/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern","type":"topic","title":"lineDashPattern","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayPathRenderer/lineDashPattern","abstract":[{"text":"An array of numbers specifying the dash pattern to use for the path.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lineDashPattern"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSNumber","text":"NSNumber"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]},"doc://com.apple.documentation/documentation/MapKit/MKOverlayPathRenderer/shouldRasterize":{"abstract":[{"text":"A Boolean value that determines whether the overlay path renderer renders the overlay as a bitmap before compositing.","type":"text"}],"url":"/documentation/MapKit/MKOverlayPathRenderer/shouldRasterize","role":"symbol","type":"topic","title":"shouldRasterize","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayPathRenderer/shouldRasterize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldRasterize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history":{"abstract":[{"text":"Continually update a MapKit overlay displaying the path a user travels.","type":"text"}],"url":"/documentation/mapkit/displaying-an-updating-path-of-a-user-s-location-history","role":"sampleCode","type":"topic","title":"Displaying an updating path of a user’s location history","identifier":"doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history","kind":"article"},"doc://com.apple.documentation/documentation/MapKit/MKOverlay":{"role":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlay","url":"/documentation/MapKit/MKOverlay","kind":"symbol","title":"MKOverlay","abstract":[{"type":"text","text":"An interface for associating content with a specific map region."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKOverlay"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation","text":"MKAnnotation"}],"type":"topic"},"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/point(for:)":{"role":"symbol","title":"point(for:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"point","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mapPoint","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapPoint","text":"MKMapPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlayRenderer/point(for:)","url":"/documentation/MapKit/MKOverlayRenderer/point(for:)","abstract":[{"text":"Returns the point in the overlay renderer’s drawing area corresponding to the specified point on the map.","type":"text"}]},"doc://com.apple.documentation/documentation/MapKit/MKMapViewDelegate/mapView(_:rendererFor:)":{"role":"symbol","type":"topic","title":"mapView(_:rendererFor:)","abstract":[{"text":"Asks the delegate for a renderer object to use when drawing the specified overlay.","type":"text"}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapViewDelegate/mapView(_:rendererFor:)","fragments":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mapView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mapView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MKMapView","text":"MKMapView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rendererFor","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"overlay","kind":"internalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)MKOverlay","text":"MKOverlay","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MKOverlayRenderer","text":"MKOverlayRenderer","kind":"typeIdentifier"}],"url":"/documentation/MapKit/MKMapViewDelegate/mapView(_:rendererFor:)","kind":"symbol"},"doc://com.apple.documentation/documentation/MapKit/MKMapView":{"fragments":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapView","kind":"identifier"}],"url":"/documentation/MapKit/MKMapView","kind":"symbol","type":"topic","role":"symbol","title":"MKMapView","abstract":[{"type":"text","text":"An embeddable map interface, similar to the one that the Maps app provides."}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapView"},"doc://com.apple.documentation/documentation/MapKit/MKOverlay/boundingMapRect":{"abstract":[{"type":"text","text":"The projected rectangle that encompasses the overlay."}],"title":"boundingMapRect","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"boundingMapRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"type":"topic","url":"/documentation/MapKit/MKOverlay/boundingMapRect","identifier":"doc://com.apple.documentation/documentation/MapKit/MKOverlay/boundingMapRect","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays":{"role":"collectionGroup","identifier":"doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays","title":"MapKit overlays","type":"topic","abstract":[{"type":"text","text":"Create overlays to highlight geographic regions or paths."}],"url":"/documentation/mapkit/mapkit-overlays","kind":"article"},"doc://com.apple.documentation/documentation/MapKit/MKMapPoint":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapPoint","kind":"identifier"}],"url":"/documentation/MapKit/MKMapPoint","kind":"symbol","type":"topic","role":"symbol","title":"MKMapPoint","abstract":[{"type":"text","text":"A point on a two-dimensional map projection."}],"identifier":"doc://com.apple.documentation/documentation/MapKit/MKMapPoint"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"/identifier/interfaceLanguage"},{"op":"add","value":null,"path":"/topicSections"},{"op":"replace","value":[{"generated":true,"title":"Samples","identifiers":["doc://com.apple.mapkit/documentation/MapKit/displaying-an-updating-path-of-a-user-s-location-history"],"anchor":"Samples"}],"path":"/seeAlsoSections"},{"op":"replace","value":"addOverlay:level:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1mapkit~1mkmapview~11452635-addoverlay/title"},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKGradientPolylineRenderer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"MKPolylineRenderer","preciseIdentifier":"c:objc(cs)MKPolylineRenderer","kind":"typeIdentifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKGradientPolylineRenderer/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMultiPolygonRenderer"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)MKOverlayPathRenderer","kind":"typeIdentifier","text":"MKOverlayPathRenderer"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMultiPolygonRenderer/fragments"},{"op":"replace","value":"overlaysInLevel:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1mapkit~1mkmapview~11452757-overlays/title"},{"op":"replace","value":"drawMapRect:zoomScale:inContext:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayRenderer~1draw(_:zoomScale:in:)/title"},{"op":"replace","value":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"drawMapRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"mapRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"zoomScale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@MKZoomScale","text":"MKZoomScale"},{"kind":"text","text":") "},{"kind":"internalParam","text":"zoomScale"},{"kind":"text","text":" "},{"kind":"identifier","text":"inContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGContextRef","text":"CGContextRef"},{"kind":"text","text":") "},{"kind":"internalParam","text":"context"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayRenderer~1draw(_:zoomScale:in:)/fragments"},{"op":"replace","value":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGBlendMode","preciseIdentifier":"c:@E@CGBlendMode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"blendMode","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayRenderer~1blendMode/fragments"},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKPolygon","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"MKMultiPoint","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MKMultiPoint"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKPolygon/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKShape"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKShape/fragments"},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKCircleRenderer","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MKOverlayPathRenderer","text":"MKOverlayPathRenderer","kind":"typeIdentifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKCircleRenderer/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMultiPoint"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MKShape","text":"MKShape"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMultiPoint/fragments"},{"op":"replace","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"MKMapRect","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapRect/fragments"},{"op":"replace","value":"kCGBlendModeColorBurn","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreGraphics~1CGBlendMode~1colorBurn/title"},{"op":"replace","value":[{"text":"kCGBlendModeColorBurn","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreGraphics~1CGBlendMode~1colorBurn/fragments"},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKCircle","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)MKShape","text":"MKShape","kind":"typeIdentifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKCircle/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMultiPolygon"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MKShape","text":"MKShape"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMultiPolygon/fragments"},{"op":"replace","value":"loadTileAtPath:result:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKTileOverlay~1loadTile(at:result:)/title"},{"op":"replace","value":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"loadTileAtPath:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@MKTileOverlayPath","text":"MKTileOverlayPath","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"path","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"result:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^)(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"tileData","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKTileOverlay~1loadTile(at:result:)/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKPolylineRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MKOverlayPathRenderer","preciseIdentifier":"c:objc(cs)MKOverlayPathRenderer"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKPolylineRenderer/fragments"},{"op":"replace","value":"kCGBlendModeScreen","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreGraphics~1CGBlendMode~1screen/title"},{"op":"replace","value":[{"text":"kCGBlendModeScreen","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreGraphics~1CGBlendMode~1screen/fragments"},{"op":"replace","value":"CGContextRef","path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreGraphics~1CGContext/title"},{"op":"replace","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGContext","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGContext"},{"text":" * ","kind":"text"},{"text":"CGContextRef","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1CoreGraphics~1CGContext/fragments"},{"op":"replace","value":"mapRectForRect:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayRenderer~1mapRect(for:)/title"},{"op":"replace","value":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect"},{"kind":"text","text":") "},{"kind":"identifier","text":"mapRectForRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayRenderer~1mapRect(for:)/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKPolygonRenderer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"MKOverlayPathRenderer","preciseIdentifier":"c:objc(cs)MKOverlayPathRenderer"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKPolygonRenderer/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKTileOverlay"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKTileOverlay/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKOverlayLevel"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayLevel/fragments"},{"op":"replace","value":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKGeoJSONDecoder","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKGeoJSONDecoder/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKTileOverlayRenderer"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)MKOverlayRenderer","kind":"typeIdentifier","text":"MKOverlayRenderer"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKTileOverlayRenderer/fragments"},{"op":"replace","value":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKAnnotation","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKAnnotation/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"CLLocationCoordinate2D","preciseIdentifier":"c:@S@CLLocationCoordinate2D"},{"kind":"text","text":" "},{"kind":"identifier","text":"coordinate"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlay~1coordinate/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKPolyline"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MKMultiPoint","text":"MKMultiPoint"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKPolyline/fragments"},{"op":"replace","value":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSNumber *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"lineDashPattern","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayPathRenderer~1lineDashPattern/fragments"},{"op":"replace","value":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"shouldRasterize","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayPathRenderer~1shouldRasterize/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKOverlay"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)MKAnnotation","text":"MKAnnotation"},{"kind":"text","text":">"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlay/fragments"},{"op":"replace","value":"pointForMapPoint:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayRenderer~1point(for:)/title"},{"op":"replace","value":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pointForMapPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapPoint","text":"MKMapPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mapPoint","kind":"internalParam"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlayRenderer~1point(for:)/fragments"},{"op":"replace","value":"mapView:rendererForOverlay:","path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:rendererFor:)/title"},{"op":"replace","value":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MKOverlayRenderer","text":"MKOverlayRenderer"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mapView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)MKMapView","text":"MKMapView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"mapView"},{"kind":"text","text":" "},{"kind":"identifier","text":"rendererForOverlay:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)MKOverlay","text":"id<MKOverlay>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"overlay"},{"kind":"text","text":";"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapViewDelegate~1mapView(_:rendererFor:)/fragments"},{"op":"replace","value":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapView"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSView","text":"NSView"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapView/fragments"},{"op":"replace","value":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"MKMapRect","kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect"},{"text":" ","kind":"text"},{"text":"boundingMapRect","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKOverlay~1boundingMapRect/fragments"},{"op":"replace","value":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"MKMapPoint","kind":"identifier"},{"text":";","kind":"text"}],"path":"/references/doc:~1~1com.apple.documentation~1documentation~1MapKit~1MKMapPoint/fragments"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}