{"identifier":{"url":"doc://com.apple.mapkit/documentation/MapKit/mapkit-for-appkit-and-uikit","interfaceLanguage":"swift"},"sections":[],"kind":"article","topicSections":[{"title":"Essentials","anchor":"Essentials","identifiers":["doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode","doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids","doc://com.apple.mapkit/documentation/MapKit/MKMapView","doc://com.apple.mapkit/documentation/MapKit/MKMapItem"]},{"title":"Map coordinates","anchor":"Map-coordinates","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion","doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan","doc://com.apple.mapkit/documentation/MapKit/MKMapRect","doc://com.apple.mapkit/documentation/MapKit/MKMapPoint","doc://com.apple.mapkit/documentation/MapKit/MKMapSize","doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter"]},{"title":"Map customization","anchor":"Map-customization","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapCamera","doc://com.apple.mapkit/documentation/MapKit/MKCompassButton","doc://com.apple.mapkit/documentation/MapKit/MKScaleView","doc://com.apple.mapkit/documentation/MapKit/MKZoomControl","doc://com.apple.mapkit/documentation/MapKit/MKPitchControl","doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingButton","doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingBarButtonItem"]},{"title":"Annotations and overlays","anchor":"Annotations-and-overlays","identifiers":["doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations","doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays"]},{"title":"Directions","anchor":"Directions","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKDirections","doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request","doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response","doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse","doc://com.apple.mapkit/documentation/MapKit/MKRoute","doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step"]},{"title":"Geographical features","anchor":"Geographical-features","identifiers":["doc://com.apple.mapkit/documentation/MapKit/displaying-an-indoor-map","doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONDecoder","doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONFeature","doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONObject"]},{"title":"Local search","anchor":"Local-search","identifiers":["doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch","doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options","doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion","doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest"]},{"title":"Exploring at street level","anchor":"Exploring-at-street-level","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene","doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest","doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController","doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter"]},{"title":"Place information","anchor":"Place-information","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate","doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController","doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle","doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory","doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle"]},{"title":"Points of interest","anchor":"Points-of-interest","identifiers":["doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids","doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation","doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions","doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest","doc://com.apple.mapkit/documentation/MapKit/MKIconStyle","doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter","doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory"]},{"title":"Static map snapshots","anchor":"Static-map-snapshots","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter","doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Snapshot"]},{"title":"Reference","anchor":"Reference","identifiers":["doc://com.apple.mapkit/documentation/MapKit/mapkit-functions"]},{"title":"Errors","anchor":"Errors","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKErrorDomain","doc://com.apple.mapkit/documentation/MapKit/MKError","doc://com.apple.mapkit/documentation/MapKit/MKError/Code"]},{"title":"Deprecated","anchor":"Deprecated","identifiers":["doc://com.apple.mapkit/documentation/MapKit/deprecated-symbols"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"collectionGroup","modules":[{"name":"MapKit"}],"roleHeading":"API Collection","title":"MapKit for AppKit and UIKit"},"variants":[{"paths":["/documentation/mapkit/mapkit-for-appkit-and-uikit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/mapkit/mapkit-for-appkit-and-uikit"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"title":"The MapKit APIs","generated":true,"anchor":"The-MapKit-APIs","identifiers":["doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui","doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mapkit/documentation/MapKit"]]},"references":{"doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"MKAddressFilter","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter","title":"MKAddressFilter","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKAddressFilter","kind":"identifier"}],"abstract":[{"type":"text","text":"An object that filters which address options to include or exclude in search results."}],"url":"/documentation/mapkit/mkaddressfilter"},"doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate":{"url":"/documentation/mapkit/mkmapitemdetailviewcontrollerdelegate","title":"MKMapItemDetailViewControllerDelegate","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"MKMapItemDetailViewControllerDelegate"}],"role":"symbol","abstract":[{"text":"The methods that you use to receive events from an associated map view controller.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapItemDetailViewControllerDelegate"}]},"doc://com.apple.mapkit/documentation/MapKit/MKDirections":{"type":"topic","title":"MKDirections","navigatorTitle":[{"text":"MKDirections","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKDirections"}],"role":"symbol","abstract":[{"text":"A utility object that computes directions and travel-time information based on the route information you provide.","type":"text"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKDirections","kind":"symbol","url":"/documentation/mapkit/mkdirections"},"doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest":{"role":"sampleCode","identifier":"doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest","url":"/documentation/mapkit/interacting-with-nearby-points-of-interest","abstract":[{"text":"Provide automatic search completions for a partial search query, search the map for relevant locations nearby, and retrieve details for selected points of interest.","type":"text"}],"kind":"article","type":"topic","title":"Interacting with nearby points of interest"},"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan":{"role":"symbol","abstract":[{"type":"text","text":"The width and height of a map region."}],"url":"/documentation/mapkit/mkcoordinatespan","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MKCoordinateSpan"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKCoordinateSpan"}],"title":"MKCoordinateSpan","type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController":{"url":"/documentation/mapkit/mkmapitemdetailviewcontroller","title":"MKMapItemDetailViewController","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController","navigatorTitle":[{"kind":"identifier","text":"MKMapItemDetailViewController"}],"role":"symbol","abstract":[{"type":"text","text":"An object that displays detailed information about a map item."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapItemDetailViewController"}]},"doc://com.apple.mapkit/documentation/MapKit":{"role":"collection","kind":"symbol","type":"topic","title":"MapKit","abstract":[{"text":"Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.","type":"text"}],"url":"/documentation/mapkit","identifier":"doc://com.apple.mapkit/documentation/MapKit"},"doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONFeature":{"url":"/documentation/mapkit/mkgeojsonfeature","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MKGeoJSONFeature","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONFeature","abstract":[{"type":"text","text":"The decoded representation of a GeoJSON feature."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKGeoJSONFeature","kind":"identifier"}],"title":"MKGeoJSONFeature","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLookAroundScene","kind":"identifier"}],"title":"MKLookAroundScene","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"MKLookAroundScene","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene","url":"/documentation/mapkit/mklookaroundscene","type":"topic","abstract":[{"type":"text","text":"A utility class that encapsulates information the framework requires to retrieve and display a specific Look Around location’s imagery."}]},"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion":{"role":"symbol","navigatorTitle":[{"text":"MKCoordinateRegion","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion","url":"/documentation/mapkit/mkcoordinateregion","kind":"symbol","title":"MKCoordinateRegion","abstract":[{"text":"A rectangular geographic region that centers around a specific latitude and longitude.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MKCoordinateRegion","kind":"identifier"}],"type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/MKIconStyle":{"url":"/documentation/mapkit/mkiconstyle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKIconStyle","kind":"identifier"}],"title":"MKIconStyle","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A class you use to customize the annotation view icon of a point of interest (POI) on the map."}],"role":"symbol","navigatorTitle":[{"text":"MKIconStyle","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKIconStyle"},"doc://com.apple.mapkit/documentation/MapKit/MKError/Code":{"type":"topic","title":"MKError.Code","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"abstract":[{"text":"Error constants for the MapKit framework.","type":"text"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKError/Code","navigatorTitle":[{"text":"Code","kind":"identifier"}],"url":"/documentation/mapkit/mkerror/code","role":"symbol","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/displaying-an-indoor-map":{"title":"Displaying an Indoor Map","role":"sampleCode","identifier":"doc://com.apple.mapkit/documentation/MapKit/displaying-an-indoor-map","type":"topic","abstract":[{"text":"Use the Indoor Mapping Data Format (IMDF) to show an indoor map with custom overlays and points of interest.","type":"text"}],"url":"/documentation/mapkit/displaying-an-indoor-map","kind":"article"},"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType":{"type":"topic","url":"/documentation/mapkit/mklocalsearchcompleter/resulttype","navigatorTitle":[{"text":"ResultType","kind":"identifier"}],"abstract":[{"text":"Options that indicate types of search completions.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ResultType","kind":"identifier"}],"role":"symbol","title":"MKLocalSearchCompleter.ResultType","kind":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType"},"doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions":{"kind":"symbol","abstract":[{"type":"text","text":"A structure you use to tell the map which kinds of features users can interact with."}],"title":"MKMapFeatureOptions","url":"/documentation/mapkit/mkmapfeatureoptions","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapFeatureOptions"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MKMapFeatureOptions"}]},"doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui":{"type":"topic","title":"MapKit for SwiftUI","url":"/documentation/mapkit/mapkit-for-swiftui","role":"collectionGroup","kind":"article","identifier":"doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui","abstract":[{"type":"text","text":"MapKit for SwiftUI allows you to build map-centric views and apps across Apple platforms. You can design expressive and highly interactive Maps with minimal code by composing views, using ViewBuilders and view modifiers."}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapPoint":{"kind":"symbol","navigatorTitle":[{"text":"MKMapPoint","kind":"identifier"}],"title":"MKMapPoint","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapPoint"}],"role":"symbol","type":"topic","url":"/documentation/mapkit/mkmappoint","abstract":[{"type":"text","text":"A point on a two-dimensional map projection."}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapPoint"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MKMapRect","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MKMapRect","kind":"identifier"}],"title":"MKMapRect","abstract":[{"text":"A rectangular area on a two-dimensional map projection.","type":"text"}],"url":"/documentation/mapkit/mkmaprect","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/mapkit-functions":{"title":"MapKit Functions","url":"/documentation/mapkit/mapkit-functions","identifier":"doc://com.apple.mapkit/documentation/MapKit/mapkit-functions","abstract":[{"text":"The functions of the MapKit framework provide convenient ways to package map-related data structures.","type":"text"}],"kind":"article","role":"collectionGroup","type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLocalSearch","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch","navigatorTitle":[{"text":"MKLocalSearch","kind":"identifier"}],"url":"/documentation/mapkit/mklocalsearch","abstract":[{"text":"A utility object for initiating map-based searches and processing the results.","type":"text"}],"kind":"symbol","type":"topic","title":"MKLocalSearch"},"adopting-unified-maps-url-thumbnail.png":{"variants":[{"traits":["2x","light"],"url":"https://docs-assets.developer.apple.com/published/9df4ca9a48bdca289a3e81586c2b963b/adopting-unified-maps-url-thumbnail%402x.png"},{"traits":["2x","dark"],"url":"https://docs-assets.developer.apple.com/published/9721b5c2679646f2a6ea75a6e00cb477/adopting-unified-maps-url-thumbnail~dark%402x.png"}],"identifier":"adopting-unified-maps-url-thumbnail.png","alt":"An image that shows a map highlighting a point of interest with an information place card.","type":"image"},"doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response":{"type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Response","kind":"identifier"}],"navigatorTitle":[{"text":"Response","kind":"identifier"}],"abstract":[{"type":"text","text":"The route information that Apple servers return in response to your request for directions."}],"kind":"symbol","role":"symbol","title":"MKDirections.Response","url":"/documentation/mapkit/mkdirections/response"},"doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter":{"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKDistanceFormatter","kind":"identifier"}],"title":"MKDistanceFormatter","abstract":[{"type":"text","text":"A utility object that converts between a geographic distance and a string-based expression of that distance."}],"url":"/documentation/mapkit/mkdistanceformatter","navigatorTitle":[{"text":"MKDistanceFormatter","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options":{"url":"/documentation/mapkit/mkaddressfilter/options","role":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Options","kind":"identifier"}],"abstract":[{"type":"text","text":"A structure that contains options for filtering results in a search."}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options","kind":"symbol","navigatorTitle":[{"text":"Options","kind":"identifier"}],"title":"MKAddressFilter.Options"},"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType":{"abstract":[{"type":"text","text":"Options that indicate types of search results."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"ResultType","kind":"identifier"}],"type":"topic","url":"/documentation/mapkit/mklocalsearch/resulttype","kind":"symbol","navigatorTitle":[{"text":"ResultType","kind":"identifier"}],"title":"MKLocalSearch.ResultType","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids":{"abstract":[{"type":"text","text":"Obtain information about a point of interest that persists over its lifetime."}],"kind":"article","role":"article","type":"topic","title":"Identifying unique locations with Place IDs","url":"/documentation/mapkit/identifying-unique-locations-with-place-ids","identifier":"doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids"},"doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse":{"type":"topic","title":"MKDirections.ETAResponse","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ETAResponse"}],"abstract":[{"type":"text","text":"The travel-time information that Apple servers return."}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse","navigatorTitle":[{"kind":"identifier","text":"ETAResponse"}],"url":"/documentation/mapkit/mkdirections/etaresponse","role":"symbol","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Snapshot":{"abstract":[{"type":"text","text":"An image that a snapshotter object generates."}],"url":"/documentation/mapkit/mkmapsnapshotter/snapshot","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Snapshot"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Snapshot","role":"symbol","title":"MKMapSnapshotter.Snapshot","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Snapshot"}],"type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request":{"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request","title":"MKDirections.Request","abstract":[{"text":"The start and end points of a route, along with the planned mode of transportation.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Request","kind":"identifier"}],"role":"symbol","url":"/documentation/mapkit/mkdirections/request","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Request","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion":{"url":"/documentation/mapkit/mklocalsearchcompletion","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MKLocalSearchCompletion","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion","abstract":[{"text":"A fully formed string that completes a partial string.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLocalSearchCompletion","kind":"identifier"}],"title":"MKLocalSearchCompletion","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapView":{"abstract":[{"type":"text","text":"An embeddable map interface, similar to the one that the Maps app provides."}],"navigatorTitle":[{"kind":"identifier","text":"MKMapView"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapView","kind":"identifier"}],"title":"MKMapView","kind":"symbol","type":"topic","url":"/documentation/mapkit/mkmapview","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapView","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays":{"role":"collectionGroup","identifier":"doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays","title":"MapKit overlays","type":"topic","abstract":[{"type":"text","text":"Create overlays to highlight geographic regions or paths."}],"url":"/documentation/mapkit/mapkit-overlays","kind":"article"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"title":"Technologies","kind":"technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies"},"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKLookAroundSceneRequest"}],"type":"topic","title":"MKLookAroundSceneRequest","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest","kind":"symbol","abstract":[{"type":"text","text":"A class you use to request a LookAround scene at the location you specify."}],"role":"symbol","url":"/documentation/mapkit/mklookaroundscenerequest","navigatorTitle":[{"kind":"identifier","text":"MKLookAroundSceneRequest"}]},"doc://com.apple.mapkit/documentation/MapKit/deprecated-symbols":{"title":"Deprecated Symbols","url":"/documentation/mapkit/deprecated-symbols","identifier":"doc://com.apple.mapkit/documentation/MapKit/deprecated-symbols","abstract":[{"text":"Map protocols and view modifiers that are no longer supported.","type":"text"}],"kind":"article","role":"collectionGroup","type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations":{"title":"MapKit annotations","url":"/documentation/mapkit/mapkit-annotations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations","abstract":[{"text":"Create annotations to add indicators and additional details for specific locations on a map.","type":"text"}]},"doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CalloutStyle"}],"type":"topic","url":"/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle/calloutstyle","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CalloutStyle"}],"title":"MKSelectionAccessory.MapItemDetailPresentationStyle.CalloutStyle","abstract":[{"text":"The style to use for a map item detail callout presentation.","type":"text"}],"role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle":{"type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle","abstract":[{"text":"The type of map item detail accessory presentation to use.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MapItemDetailPresentationStyle"}],"role":"symbol","title":"MKSelectionAccessory.MapItemDetailPresentationStyle","url":"/documentation/mapkit/mkselectionaccessory/mapitemdetailpresentationstyle","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MapItemDetailPresentationStyle"}]},"doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode":{"abstract":[{"text":"Configure your routing app to support providing directions.","type":"text"}],"role":"article","url":"/documentation/mapkit/enabling-maps-capability-in-xcode","kind":"article","type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode","title":"Enabling Maps capability in Xcode"},"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController":{"abstract":[{"type":"text","text":"A class that manages the presentation and display of a LookAround view."}],"navigatorTitle":[{"text":"MKLookAroundViewController","kind":"identifier"}],"title":"MKLookAroundViewController","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController","url":"/documentation/mapkit/mklookaroundviewcontroller","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLookAroundViewController","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapItem":{"url":"/documentation/mapkit/mkmapitem","kind":"symbol","title":"MKMapItem","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapItem","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapItem"}],"type":"topic","abstract":[{"type":"text","text":"A point of interest on the map."}],"navigatorTitle":[{"kind":"identifier","text":"MKMapItem"}]},"doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingButton":{"role":"symbol","kind":"symbol","title":"MKUserTrackingButton","type":"topic","abstract":[{"text":"A specialized button that allows the user to toggle whether the map tracks to the heading the user is facing.","type":"text"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingButton","navigatorTitle":[{"text":"MKUserTrackingButton","kind":"identifier"}],"url":"/documentation/mapkit/mkusertrackingbutton","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKUserTrackingButton","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKError":{"type":"topic","abstract":[{"text":"Error constants for the MapKit framework.","type":"text"}],"title":"MKError","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKError","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKError","role":"symbol","url":"/documentation/mapkit/mkerror","kind":"symbol","navigatorTitle":[{"text":"MKError","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step":{"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step","title":"MKRoute.Step","abstract":[{"type":"text","text":"One portion of an overall route."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Step"}],"role":"symbol","url":"/documentation/mapkit/mkroute/step","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Step"}]},"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLocalSearchRegionPriority","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority","navigatorTitle":[{"text":"MKLocalSearchRegionPriority","kind":"identifier"}],"url":"/documentation/mapkit/mklocalsearchregionpriority","abstract":[{"text":"A value that indicates the importance of the configured region.","type":"text"}],"kind":"symbol","type":"topic","title":"MKLocalSearchRegionPriority"},"doc://com.apple.mapkit/documentation/MapKit/MKRoute":{"url":"/documentation/mapkit/mkroute","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MKRoute","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKRoute","abstract":[{"text":"A single route between a requested start and end point.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKRoute","kind":"identifier"}],"title":"MKRoute","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKZoomControl":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKZoomControl","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKZoomControl","role":"symbol","type":"topic","navigatorTitle":[{"text":"MKZoomControl","kind":"identifier"}],"abstract":[{"text":"A specialized view that displays and controls the zoom level of the map view.","type":"text"}],"url":"/documentation/mapkit/mkzoomcontrol","title":"MKZoomControl"},"doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONObject":{"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONObject","title":"MKGeoJSONObject","abstract":[{"type":"text","text":"Objects that the GeoJSON decoder can return."}],"url":"/documentation/mapkit/mkgeojsonobject","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKGeoJSONObject"}],"navigatorTitle":[{"kind":"identifier","text":"MKGeoJSONObject"}],"kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation":{"abstract":[{"type":"text","text":"A class that describes an annotation element on the map’s display such as a point of interest, territorial boundary, or physical feature."}],"navigatorTitle":[{"kind":"identifier","text":"MKMapFeatureAnnotation"}],"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation","url":"/documentation/mapkit/mkmapfeatureannotation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapFeatureAnnotation"}],"type":"topic","title":"MKMapFeatureAnnotation","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter":{"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter","abstract":[{"text":"A utility class that you use to create a static image from a LookAround scene.","type":"text"}],"title":"MKLookAroundSnapshotter","kind":"symbol","type":"topic","role":"symbol","url":"/documentation/mapkit/mklookaroundsnapshotter","navigatorTitle":[{"text":"MKLookAroundSnapshotter","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLookAroundSnapshotter","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory":{"role":"symbol","abstract":[{"type":"text","text":"A point of interest category."}],"url":"/documentation/mapkit/mkpointofinterestcategory","navigatorTitle":[{"kind":"identifier","text":"MKPointOfInterestCategory"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory","kind":"symbol","type":"topic","title":"MKPointOfInterestCategory","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKPointOfInterestCategory"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter":{"type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter","abstract":[{"text":"A utility class for capturing a map and its content into an image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapSnapshotter"}],"role":"symbol","title":"MKMapSnapshotter","url":"/documentation/mapkit/mkmapsnapshotter","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapSnapshotter"}]},"doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter":{"navigatorTitle":[{"kind":"identifier","text":"MKPointOfInterestFilter"}],"type":"topic","title":"MKPointOfInterestFilter","url":"/documentation/mapkit/mkpointofinterestfilter","abstract":[{"text":"A filter that includes or excludes point of interest categories from a map view, local search, or local search completer.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MKPointOfInterestFilter"}],"kind":"symbol","role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter"},"doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKLocalPointsOfInterestRequest","kind":"identifier"}],"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest","navigatorTitle":[{"text":"MKLocalPointsOfInterestRequest","kind":"identifier"}],"url":"/documentation/mapkit/mklocalpointsofinterestrequest","abstract":[{"text":"A structured request to use when searching for points of interest.","type":"text"}],"kind":"symbol","type":"topic","title":"MKLocalPointsOfInterestRequest"},"doc://com.apple.mapkit/documentation/MapKit/MKPitchControl":{"kind":"symbol","url":"/documentation/mapkit/mkpitchcontrol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKPitchControl","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKPitchControl","kind":"identifier"}],"navigatorTitle":[{"text":"MKPitchControl","kind":"identifier"}],"type":"topic","title":"MKPitchControl","abstract":[{"text":"A specialized view that displays and controls the pitch angle of the map view.","type":"text"}]},"doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingBarButtonItem":{"role":"symbol","kind":"symbol","title":"MKUserTrackingBarButtonItem","type":"topic","abstract":[{"text":"A specialized bar button item that allows the user to toggle whether the map tracks to the heading the user is facing.","type":"text"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingBarButtonItem","navigatorTitle":[{"text":"MKUserTrackingBarButtonItem","kind":"identifier"}],"url":"/documentation/mapkit/mkusertrackingbarbuttonitem","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKUserTrackingBarButtonItem","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKErrorDomain":{"kind":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKErrorDomain","abstract":[{"type":"text","text":"The error domain for MapKit."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MKErrorDomain"}],"url":"/documentation/mapkit/mkerrordomain","title":"MKErrorDomain","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONDecoder":{"navigatorTitle":[{"text":"MKGeoJSONDecoder","kind":"identifier"}],"title":"MKGeoJSONDecoder","type":"topic","url":"/documentation/mapkit/mkgeojsondecoder","abstract":[{"text":"An object that decodes GeoJSON objects into MapKit types.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKGeoJSONDecoder","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONDecoder","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest":{"type":"topic","abstract":[{"text":"A utility class you use to request additional information about a map feature.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapItemRequest"}],"url":"/documentation/mapkit/mkmapitemrequest","navigatorTitle":[{"kind":"identifier","text":"MKMapItemRequest"}],"title":"MKMapItemRequest","role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest"},"doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory":{"url":"/documentation/mapkit/mkselectionaccessory","kind":"symbol","title":"MKSelectionAccessory","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKSelectionAccessory","kind":"identifier"}],"type":"topic","abstract":[{"text":"The type of accessory to display for a selected annotation.","type":"text"}],"navigatorTitle":[{"text":"MKSelectionAccessory","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKScaleView":{"url":"/documentation/mapkit/mkscaleview","navigatorTitle":[{"text":"MKScaleView","kind":"identifier"}],"role":"symbol","title":"MKScaleView","abstract":[{"text":"A specialized view that displays the scale information for its associated map.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKScaleView","kind":"identifier"}],"kind":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKScaleView"},"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter":{"title":"MKLocalSearchCompleter","role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter","navigatorTitle":[{"kind":"identifier","text":"MKLocalSearchCompleter"}],"type":"topic","abstract":[{"text":"A utility object for generating a list of completion strings based on a partial search string that you provide.","type":"text"}],"url":"/documentation/mapkit/mklocalsearchcompleter","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKLocalSearchCompleter"}]},"doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs":{"type":"topic","title":"Adopting unified Maps URLs","url":"/documentation/mapkit/unified-map-urls","abstract":[{"text":"Access Maps URLs and options for displaying Maps information across Apple platforms.","type":"text"}],"role":"article","kind":"article","images":[{"type":"card","identifier":"adopting-unified-maps-url-thumbnail.png"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs"},"doc://com.apple.mapkit/documentation/MapKit/MKMapCamera":{"kind":"symbol","abstract":[{"text":"A virtual camera for defining the appearance of the map.","type":"text"}],"title":"MKMapCamera","url":"/documentation/mapkit/mkmapcamera","role":"symbol","type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapCamera","navigatorTitle":[{"text":"MKMapCamera","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapCamera","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKCompassButton":{"type":"topic","navigatorTitle":[{"text":"MKCompassButton","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKCompassButton","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKCompassButton","url":"/documentation/mapkit/mkcompassbutton","role":"symbol","kind":"symbol","abstract":[{"text":"A specialized view that displays the compass heading for its associated map.","type":"text"}],"title":"MKCompassButton"},"doc://com.apple.mapkit/documentation/MapKit/MKMapSize":{"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapSize","abstract":[{"type":"text","text":"Width and height information on a two-dimensional map projection."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapSize","kind":"identifier"}],"title":"MKMapSize","role":"symbol","url":"/documentation/mapkit/mkmapsize","kind":"symbol","navigatorTitle":[{"text":"MKMapSize","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"/identifier/interfaceLanguage","op":"replace"},{"value":[{"title":"Essentials","identifiers":["doc://com.apple.mapkit/documentation/MapKit/enabling-maps-capability-in-xcode","doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids","doc://com.apple.mapkit/documentation/MapKit/MKMapView","doc://com.apple.mapkit/documentation/MapKit/MKMapItem"],"anchor":"Essentials"},{"title":"Map coordinates","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion","doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan","doc://com.apple.mapkit/documentation/MapKit/MKMapRect","doc://com.apple.mapkit/documentation/MapKit/MKMapPoint","doc://com.apple.mapkit/documentation/MapKit/MKMapSize","doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter"],"anchor":"Map-coordinates"},{"title":"Map customization","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapCamera","doc://com.apple.mapkit/documentation/MapKit/MKCompassButton","doc://com.apple.mapkit/documentation/MapKit/MKScaleView","doc://com.apple.mapkit/documentation/MapKit/MKZoomControl","doc://com.apple.mapkit/documentation/MapKit/MKPitchControl","doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingButton","doc://com.apple.mapkit/documentation/MapKit/MKUserTrackingBarButtonItem"],"anchor":"Map-customization"},{"title":"Annotations and overlays","identifiers":["doc://com.apple.mapkit/documentation/MapKit/mapkit-annotations","doc://com.apple.mapkit/documentation/MapKit/mapkit-overlays"],"anchor":"Annotations-and-overlays"},{"title":"Directions","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKDirections","doc://com.apple.mapkit/documentation/MapKit/MKDirections/Request","doc://com.apple.mapkit/documentation/MapKit/MKDirections/Response","doc://com.apple.mapkit/documentation/MapKit/MKDirections/ETAResponse","doc://com.apple.mapkit/documentation/MapKit/MKRoute","doc://com.apple.mapkit/documentation/MapKit/MKRoute/Step"],"anchor":"Directions"},{"title":"Geographical features","identifiers":["doc://com.apple.mapkit/documentation/MapKit/displaying-an-indoor-map","doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONDecoder","doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONFeature","doc://com.apple.mapkit/documentation/MapKit/MKGeoJSONObject"],"anchor":"Geographical-features"},{"title":"Local search","identifiers":["doc://com.apple.mapkit/documentation/MapKit/interacting-with-nearby-points-of-interest","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchRegionPriority","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch/ResultType","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearch","doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter/Options","doc://com.apple.mapkit/documentation/MapKit/MKAddressFilter","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter/ResultType","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompleter","doc://com.apple.mapkit/documentation/MapKit/MKLocalSearchCompletion","doc://com.apple.mapkit/documentation/MapKit/MKLocalPointsOfInterestRequest"],"anchor":"Local-search"},{"title":"Exploring at street level","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKLookAroundScene","doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSceneRequest","doc://com.apple.mapkit/documentation/MapKit/MKLookAroundViewController","doc://com.apple.mapkit/documentation/MapKit/MKLookAroundSnapshotter"],"anchor":"Exploring-at-street-level"},{"title":"Place information","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewControllerDelegate","doc://com.apple.mapkit/documentation/MapKit/MKMapItemDetailViewController","doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle","doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory","doc://com.apple.mapkit/documentation/MapKit/MKSelectionAccessory/MapItemDetailPresentationStyle/CalloutStyle"],"anchor":"Place-information"},{"title":"Points of interest","identifiers":["doc://com.apple.mapkit/documentation/MapKit/identifying-unique-locations-with-place-ids","doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureAnnotation","doc://com.apple.mapkit/documentation/MapKit/MKMapFeatureOptions","doc://com.apple.mapkit/documentation/MapKit/MKMapItemRequest","doc://com.apple.mapkit/documentation/MapKit/MKIconStyle","doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestFilter","doc://com.apple.mapkit/documentation/MapKit/MKPointOfInterestCategory"],"anchor":"Points-of-interest"},{"title":"Static map snapshots","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter","doc://com.apple.mapkit/documentation/MapKit/MKMapSnapshotter/Snapshot"],"anchor":"Static-map-snapshots"},{"title":"Reference","identifiers":["doc://com.apple.mapkit/documentation/MapKit/mapkit-functions"],"anchor":"Reference"},{"title":"Errors","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKErrorDomain","doc://com.apple.mapkit/documentation/MapKit/MKError/Code"],"anchor":"Errors"},{"title":"Deprecated","identifiers":["doc://com.apple.mapkit/documentation/MapKit/deprecated-symbols"],"anchor":"Deprecated"}],"path":"/topicSections","op":"replace"},{"value":[{"identifiers":["doc://com.apple.mapkit/documentation/MapKit/mapkit-for-swiftui","doc://com.apple.mapkit/documentation/MapKit/Unified-Map-URLs"],"generated":true,"anchor":"The-MapKit-APIs","title":"The MapKit APIs"}],"path":"/seeAlsoSections","op":"replace"},{"value":"MKAddressFilter","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKAddressFilter"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/fragments","op":"replace"},{"value":[{"text":"MKAddressFilter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter/navigatorTitle","op":"replace"},{"value":"MKMapItemDetailViewControllerDelegate","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItemDetailViewControllerDelegate"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItemDetailViewControllerDelegate"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewControllerDelegate/navigatorTitle","op":"replace"},{"value":"MKDirections","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKDirections"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKDirections"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections/navigatorTitle","op":"replace"},{"value":"MKCoordinateSpan","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/title","op":"replace"},{"value":[{"text":"MKCoordinateSpan","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKCoordinateSpan"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/navigatorTitle","op":"replace"},{"value":"MKMapItemDetailViewController","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/title","op":"replace"},{"value":[{"text":"MKMapItemDetailViewController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/fragments","op":"replace"},{"value":[{"text":"MKMapItemDetailViewController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemDetailViewController/navigatorTitle","op":"replace"},{"value":"MKGeoJSONFeature","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONFeature/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKGeoJSONFeature"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONFeature/fragments","op":"replace"},{"value":[{"text":"MKGeoJSONFeature","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONFeature/navigatorTitle","op":"replace"},{"value":"MKLookAroundScene","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/title","op":"replace"},{"value":[{"text":"MKLookAroundScene","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/fragments","op":"replace"},{"value":[{"text":"MKLookAroundScene","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundScene/navigatorTitle","op":"replace"},{"value":"MKCoordinateRegion","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/title","op":"replace"},{"value":[{"text":"MKCoordinateRegion","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/fragments","op":"replace"},{"value":[{"text":"MKCoordinateRegion","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/navigatorTitle","op":"replace"},{"value":"MKIconStyle","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKIconStyle"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKIconStyle"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKIconStyle/navigatorTitle","op":"replace"},{"value":"MKErrorCode","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKError~1Code/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKErrorCode"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKError~1Code/fragments","op":"replace"},{"value":[{"text":"MKErrorCode","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKError~1Code/navigatorTitle","op":"replace"},{"value":"MKLocalSearchCompleterResultType","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalSearchCompleterResultType"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/fragments","op":"replace"},{"value":[{"text":"MKLocalSearchCompleterResultType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter~1ResultType/navigatorTitle","op":"replace"},{"value":"MKMapFeatureOptions","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapFeatureOptions"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapFeatureOptions"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureOptions/navigatorTitle","op":"replace"},{"value":"MKMapPoint","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapPoint"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/fragments","op":"replace"},{"value":[{"text":"MKMapPoint","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/navigatorTitle","op":"replace"},{"value":"MKMapRect","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/title","op":"replace"},{"value":[{"text":"MKMapRect","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapRect"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/navigatorTitle","op":"replace"},{"value":"MKLocalSearch","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalSearch"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch/fragments","op":"replace"},{"value":[{"text":"MKLocalSearch","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch/navigatorTitle","op":"replace"},{"value":"MKDirectionsResponse","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Response/title","op":"replace"},{"value":[{"text":"MKDirectionsResponse","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Response/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKDirectionsResponse"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Response/navigatorTitle","op":"replace"},{"value":"MKDistanceFormatter","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKDistanceFormatter"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/fragments","op":"replace"},{"value":[{"text":"MKDistanceFormatter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/navigatorTitle","op":"replace"},{"value":"MKAddressFilterOption","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKAddressFilterOption"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKAddressFilterOption"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKAddressFilter~1Options/navigatorTitle","op":"replace"},{"value":"MKLocalSearchResultType","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch~1ResultType/title","op":"replace"},{"value":[{"text":"MKLocalSearchResultType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch~1ResultType/fragments","op":"replace"},{"value":[{"text":"MKLocalSearchResultType","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearch~1ResultType/navigatorTitle","op":"replace"},{"value":"MKETAResponse","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1ETAResponse/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKETAResponse"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1ETAResponse/fragments","op":"replace"},{"value":[{"text":"MKETAResponse","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1ETAResponse/navigatorTitle","op":"replace"},{"value":"MKMapSnapshot","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Snapshot/title","op":"replace"},{"value":[{"text":"MKMapSnapshot","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Snapshot/fragments","op":"replace"},{"value":[{"text":"MKMapSnapshot","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter~1Snapshot/navigatorTitle","op":"replace"},{"value":"MKDirectionsRequest","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKDirectionsRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKDirectionsRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDirections~1Request/navigatorTitle","op":"replace"},{"value":"MKLocalSearchCompletion","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalSearchCompletion"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/fragments","op":"replace"},{"value":[{"text":"MKLocalSearchCompletion","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompletion/navigatorTitle","op":"replace"},{"value":"MKMapView","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapView"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapView"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapView/navigatorTitle","op":"replace"},{"value":"MKLookAroundSceneRequest","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKLookAroundSceneRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKLookAroundSceneRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSceneRequest/navigatorTitle","op":"replace"},{"value":"MKMapItemDetailSelectionAccessoryCalloutStyle","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItemDetailSelectionAccessoryCalloutStyle"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItemDetailSelectionAccessoryCalloutStyle"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle~1CalloutStyle/navigatorTitle","op":"replace"},{"value":"MKMapItemDetailSelectionAccessoryPresentationStyle","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/title","op":"replace"},{"value":[{"text":"MKMapItemDetailSelectionAccessoryPresentationStyle","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItemDetailSelectionAccessoryPresentationStyle"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory~1MapItemDetailPresentationStyle/navigatorTitle","op":"replace"},{"value":"MKLookAroundViewController","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController/title","op":"replace"},{"value":[{"text":"MKLookAroundViewController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController/fragments","op":"replace"},{"value":[{"text":"MKLookAroundViewController","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundViewController/navigatorTitle","op":"replace"},{"value":"MKMapItem","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/title","op":"replace"},{"value":[{"text":"MKMapItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItem"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItem/navigatorTitle","op":"replace"},{"value":"MKUserTrackingButton","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserTrackingButton/title","op":"replace"},{"value":[{"text":"MKUserTrackingButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserTrackingButton/fragments","op":"replace"},{"value":[{"text":"MKUserTrackingButton","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserTrackingButton/navigatorTitle","op":"replace"},{"value":"MKRouteStep","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute~1Step/title","op":"replace"},{"value":[{"text":"MKRouteStep","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute~1Step/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKRouteStep"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute~1Step/navigatorTitle","op":"replace"},{"value":"MKLocalSearchRegionPriority","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchRegionPriority/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalSearchRegionPriority"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchRegionPriority/fragments","op":"replace"},{"value":[{"text":"MKLocalSearchRegionPriority","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchRegionPriority/navigatorTitle","op":"replace"},{"value":"MKRoute","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute/title","op":"replace"},{"value":[{"text":"MKRoute","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKRoute"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKRoute/navigatorTitle","op":"replace"},{"value":"MKZoomControl","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKZoomControl/title","op":"replace"},{"value":[{"text":"MKZoomControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKZoomControl/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKZoomControl"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKZoomControl/navigatorTitle","op":"replace"},{"value":"MKGeoJSONObject","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONObject/title","op":"replace"},{"value":[{"text":"MKGeoJSONObject","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONObject/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKGeoJSONObject"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONObject/navigatorTitle","op":"replace"},{"value":"MKMapFeatureAnnotation","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapFeatureAnnotation"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapFeatureAnnotation"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapFeatureAnnotation/navigatorTitle","op":"replace"},{"value":"MKLookAroundSnapshotter","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSnapshotter/title","op":"replace"},{"value":[{"text":"MKLookAroundSnapshotter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSnapshotter/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKLookAroundSnapshotter"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLookAroundSnapshotter/navigatorTitle","op":"replace"},{"value":"MKPointOfInterestCategory","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKPointOfInterestCategory"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKPointOfInterestCategory"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestCategory/navigatorTitle","op":"replace"},{"value":"MKMapSnapshotter","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/title","op":"replace"},{"value":[{"text":"MKMapSnapshotter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapSnapshotter"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSnapshotter/navigatorTitle","op":"replace"},{"value":"MKPointOfInterestFilter","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/title","op":"replace"},{"value":[{"text":"MKPointOfInterestFilter","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKPointOfInterestFilter"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPointOfInterestFilter/navigatorTitle","op":"replace"},{"value":"MKLocalPointsOfInterestRequest","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalPointsOfInterestRequest/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalPointsOfInterestRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalPointsOfInterestRequest/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalPointsOfInterestRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalPointsOfInterestRequest/navigatorTitle","op":"replace"},{"value":"MKPitchControl","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPitchControl/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKPitchControl"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPitchControl/fragments","op":"replace"},{"value":[{"text":"MKPitchControl","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKPitchControl/navigatorTitle","op":"replace"},{"value":"MKUserTrackingBarButtonItem","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserTrackingBarButtonItem/title","op":"replace"},{"value":[{"text":"MKUserTrackingBarButtonItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserTrackingBarButtonItem/fragments","op":"replace"},{"value":[{"text":"MKUserTrackingBarButtonItem","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKUserTrackingBarButtonItem/navigatorTitle","op":"replace"},{"value":"MKErrorDomain","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKErrorDomain/title","op":"replace"},{"value":[{"text":"MKErrorDomain","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKErrorDomain/fragments","op":"replace"},{"value":"MKGeoJSONDecoder","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONDecoder/title","op":"replace"},{"value":[{"text":"MKGeoJSONDecoder","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONDecoder/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKGeoJSONDecoder"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKGeoJSONDecoder/navigatorTitle","op":"replace"},{"value":"MKMapItemRequest","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItemRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKMapItemRequest"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapItemRequest/navigatorTitle","op":"replace"},{"value":"MKSelectionAccessory","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKSelectionAccessory"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/fragments","op":"replace"},{"value":[{"text":"MKSelectionAccessory","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKSelectionAccessory/navigatorTitle","op":"replace"},{"value":"MKScaleView","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKScaleView/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKScaleView"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKScaleView/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKScaleView"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKScaleView/navigatorTitle","op":"replace"},{"value":"MKLocalSearchCompleter","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalSearchCompleter"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKLocalSearchCompleter"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKLocalSearchCompleter/navigatorTitle","op":"replace"},{"value":"MKMapCamera","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapCamera/title","op":"replace"},{"value":[{"text":"MKMapCamera","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapCamera/fragments","op":"replace"},{"value":[{"text":"MKMapCamera","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapCamera/navigatorTitle","op":"replace"},{"value":"MKCompassButton","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCompassButton/title","op":"replace"},{"value":[{"kind":"identifier","text":"MKCompassButton"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCompassButton/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"MKCompassButton"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCompassButton/navigatorTitle","op":"replace"},{"value":"MKMapSize","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/title","op":"replace"},{"value":[{"text":"MKMapSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/fragments","op":"replace"},{"value":[{"text":"MKMapSize","kind":"identifier"}],"path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}],"diffAvailability":{"major":{"change":"modified","platform":"Xcode","versions":["16.0","16.3"]}},"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}