{"topicSections":[{"title":"Creating a map rectangle","anchor":"Creating-a-map-rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init()","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init(origin:size:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init(x:y:width:height:)","doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion/init(_:)"]},{"title":"Getting standard map rectangles","anchor":"Getting-standard-map-rectangles","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/null","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/world"]},{"title":"Getting the rectangle coordinates","anchor":"Getting-the-rectangle-coordinates","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/origin","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/size"]},{"title":"Getting the boundaries","anchor":"Getting-the-boundaries","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minX","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minY","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midX","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midY","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxX","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxY","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/width","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/height"]},{"title":"Comparing rectangles","anchor":"Comparing-rectangles","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isNull","doc://com.apple.mapkit/documentation/MapKit/MKMapRectEqualToRect(_:_:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isEmpty","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/spans180thMeridian","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/remainder"]},{"title":"Intersecting the rectangle","anchor":"Intersecting-the-rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-79tjt","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-1z5oa","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersects(_:)"]},{"title":"Modifying the rectangle","anchor":"Modifying-the-rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/union(_:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersection(_:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/insetBy(dx:dy:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/offsetBy(dx:dy:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRectDivide(_:_:_:_:_:)"]},{"title":"Getting a description of the rectangle","anchor":"Getting-a-description-of-the-rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapRect(_:)"]}],"seeAlsoSections":[{"generated":true,"title":"Map coordinates","anchor":"Map-coordinates","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion","doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan","doc://com.apple.mapkit/documentation/MapKit/MKMapPoint","doc://com.apple.mapkit/documentation/MapKit/MKMapSize","doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter"]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP","doc://com.externally.resolved.symbol/s:s8SendableP"]}],"hierarchy":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mapkit/documentation/MapKit"]]},"kind":"symbol","metadata":{"modules":[{"name":"MapKit"}],"symbolKind":"struct","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapRect","kind":"identifier"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false},{"unavailable":false,"deprecated":false,"name":"Mac Catalyst","beta":false},{"unavailable":false,"deprecated":false,"name":"macOS","beta":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"deprecated":false,"name":"watchOS","beta":false}],"externalID":"c:@SA@MKMapRect","roleHeading":"Structure","title":"MKMapRect","navigatorTitle":[{"text":"MKMapRect","kind":"identifier"}]},"abstract":[{"type":"text","text":"A rectangular area on a two-dimensional map projection."}],"sections":[],"variants":[{"paths":["/documentation/mapkit/mkmaprect"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["/documentation/mapkit/mkmaprect"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapRect"}],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"If you project the curved surface of the globe onto a flat surface, what you get is a two-dimensional version of a map where longitude lines appear to be parallel. Such maps are often used to show the entire surface of the globe all at once. An ","type":"text"},{"code":"MKMapRect","type":"codeVoice"},{"text":" data structure represents a rectangular area as seen on this two-dimensional map.","type":"text"}]}]}],"references":{"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/spans180thMeridian":{"kind":"symbol","title":"spans180thMeridian","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/spans180thMeridian","type":"topic","role":"symbol","abstract":[{"text":"A Boolean value that indicates whether the specified map rectangle crosses the 180th meridian.","type":"text"}],"url":"/documentation/mapkit/mkmaprect/spans180thmeridian","navigatorTitle":[{"text":"MKMapRectSpans180thMeridian","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"spans180thMeridian","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init(origin:size:)":{"type":"topic","role":"symbol","title":"init(origin:size:)","abstract":[{"text":"Creates the map rectangle with the specified point and size.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init(origin:size:)","url":"/documentation/mapkit/mkmaprect/init(origin:size:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"origin","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@MKMapPoint","kind":"typeIdentifier","text":"MKMapPoint"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MKMapSize","preciseIdentifier":"c:@SA@MKMapSize"},{"kind":"text","text":")"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-1z5oa":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"contains"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol","url":"/documentation/mapkit/mkmaprect/contains(_:)-1z5oa","abstract":[{"text":"Returns a Boolean value that indicates whether one rectangle contains another.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectContainsRect"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-1z5oa","type":"topic","title":"contains(_:)"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init()":{"type":"topic","role":"symbol","title":"init()","abstract":[{"text":"Creates the rectangle with an empty region.","type":"text"}],"kind":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init()","url":"/documentation/mapkit/mkmaprect/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-79tjt":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contains","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapPoint","text":"MKMapPoint","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","kind":"symbol","url":"/documentation/mapkit/mkmaprect/contains(_:)-79tjt","abstract":[{"text":"Returns a Boolean value that indicates whether the specified map point lies within the rectangle.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectContainsPoint"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-79tjt","type":"topic","title":"contains(_:)"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/remainder":{"kind":"symbol","title":"remainder","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/remainder","type":"topic","role":"symbol","abstract":[{"text":"A rectangle that represents the normalized portion of the specified rectangle that lies outside the world map boundaries.","type":"text"}],"url":"/documentation/mapkit/mkmaprect/remainder","navigatorTitle":[{"text":"MKMapRectRemainder","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remainder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect","kind":"typeIdentifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minY":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minY","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns the minimum y-axis value of the specified rectangle."}],"navigatorTitle":[{"text":"MKMapRectGetMinY","kind":"identifier"}],"title":"minY","url":"/documentation/mapkit/mkmaprect/miny","role":"symbol","type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minY","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/world":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"world"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"}],"role":"symbol","kind":"symbol","url":"/documentation/mapkit/mkmaprect/world","abstract":[{"type":"text","text":"The map rectangle that represents the world in the two-dimensional map projection."}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectWorld"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/world","type":"topic","title":"world"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersects(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"intersects"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MKMapRect","preciseIdentifier":"c:@SA@MKMapRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","kind":"symbol","url":"/documentation/mapkit/mkmaprect/intersects(_:)","abstract":[{"text":"Returns a Boolean value that indicates whether two rectangles intersect each other.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectIntersectsRect"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersects(_:)","type":"topic","title":"intersects(_:)"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRectDivide(_:_:_:_:_:)":{"kind":"symbol","role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRectDivide(_:_:_:_:_:)","abstract":[{"type":"text","text":"Divides the specified rectangle into two smaller rectangles."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapRectDivide"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:Sp","kind":"typeIdentifier","text":"UnsafeMutablePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"},{"kind":"text","text":">, "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@E@CGRectEdge","kind":"typeIdentifier","text":"CGRectEdge"},{"kind":"text","text":")"}],"url":"/documentation/mapkit/mkmaprectdivide(_:_:_:_:_:)","type":"topic","title":"MKMapRectDivide(_:_:_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"MKMapRectDivide"}]},"doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter":{"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKDistanceFormatter","kind":"identifier"}],"title":"MKDistanceFormatter","abstract":[{"type":"text","text":"A utility object that converts between a geographic distance and a string-based expression of that distance."}],"url":"/documentation/mapkit/mkdistanceformatter","navigatorTitle":[{"text":"MKDistanceFormatter","kind":"identifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/size":{"url":"/documentation/mapkit/mkmaprect/size","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MKMapSize","preciseIdentifier":"c:@SA@MKMapSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/size","kind":"symbol","title":"size","role":"symbol","abstract":[{"type":"text","text":"The width and height of the rectangle, starting from the origin point."}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init(x:y:width:height:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates a new map rectangle structure from the specified values."}],"title":"init(x:y:width:height:)","type":"topic","navigatorTitle":[{"text":"MKMapRectMake","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init(x:y:width:height:)","kind":"symbol","role":"symbol","url":"/documentation/mapkit/mkmaprect/init(x:y:width:height:)"},"doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapRect(_:)":{"url":"/documentation/mapkit/mkstringfrommaprect(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MKStringFromMapRect"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"MKStringFromMapRect"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapRect(_:)","kind":"symbol","title":"MKStringFromMapRect(_:)","role":"symbol","abstract":[{"type":"text","text":"Returns a formatted string for the specified map rectangle."}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MKMapRect","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"MKMapRect","kind":"identifier"}],"title":"MKMapRect","abstract":[{"text":"A rectangular area on a two-dimensional map projection.","type":"text"}],"url":"/documentation/mapkit/mkmaprect","role":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion":{"role":"symbol","navigatorTitle":[{"text":"MKCoordinateRegion","kind":"identifier"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion","url":"/documentation/mapkit/mkcoordinateregion","kind":"symbol","title":"MKCoordinateRegion","abstract":[{"text":"A rectangular geographic region that centers around a specific latitude and longitude.","type":"text"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"MKCoordinateRegion","kind":"identifier"}],"type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minX":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minX","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns the minimum x-axis value of the specified rectangle."}],"navigatorTitle":[{"text":"MKMapRectGetMinX","kind":"identifier"}],"title":"minX","url":"/documentation/mapkit/mkmaprect/minx","role":"symbol","type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minX","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isEmpty":{"kind":"symbol","title":"isEmpty","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isEmpty","type":"topic","role":"symbol","abstract":[{"text":"A Boolean value that indicates whether the specified rectangle has no area.","type":"text"}],"url":"/documentation/mapkit/mkmaprect/isempty","navigatorTitle":[{"text":"MKMapRectIsEmpty","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion/init(_:)":{"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion/init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"MKCoordinateRegionForMapRect"}],"role":"symbol","type":"topic","url":"/documentation/mapkit/mkcoordinateregion/init(_:)","kind":"symbol","title":"init(_:)","abstract":[{"type":"text","text":"Returns the region that corresponds to the specified map rectangle."}]},"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan":{"role":"symbol","abstract":[{"type":"text","text":"The width and height of a map region."}],"url":"/documentation/mapkit/mkcoordinatespan","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MKCoordinateSpan"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKCoordinateSpan"}],"title":"MKCoordinateSpan","type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/union(_:)":{"url":"/documentation/mapkit/mkmaprect/union(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"union"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectUnion"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/union(_:)","kind":"symbol","title":"union(_:)","role":"symbol","abstract":[{"type":"text","text":"Returns a rectangle that represents the union of two rectangles."}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/offsetBy(dx:dy:)":{"url":"/documentation/mapkit/mkmaprect/offsetby(dx:dy:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"offsetBy"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dx"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dy"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectOffset"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/offsetBy(dx:dy:)","kind":"symbol","title":"offsetBy(dx:dy:)","role":"symbol","abstract":[{"type":"text","text":"Returns a rectangle with an origin point that shifts by the specified amount."}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isNull":{"kind":"symbol","title":"isNull","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isNull","type":"topic","role":"symbol","abstract":[{"text":"A Boolean value that indicates whether the specified rectangle is null.","type":"text"}],"url":"/documentation/mapkit/mkmaprect/isnull","navigatorTitle":[{"text":"MKMapRectIsNull","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNull","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRectEqualToRect(_:_:)":{"kind":"symbol","title":"MKMapRectEqualToRect(_:_:)","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRectEqualToRect(_:_:)","type":"topic","role":"symbol","abstract":[{"text":"Returns a Boolean value that indicates whether two map rectangles are equal.","type":"text"}],"url":"/documentation/mapkit/mkmaprectequaltorect(_:_:)","navigatorTitle":[{"text":"MKMapRectEqualToRect","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapRectEqualToRect","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapRect","text":"MKMapRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxY":{"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxY","type":"topic","navigatorTitle":[{"text":"MKMapRectGetMaxY","kind":"identifier"}],"title":"maxY","abstract":[{"text":"Returns the maximum y-axis value of the specified rectangle.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxY","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"/documentation/mapkit/mkmaprect/maxy","kind":"symbol"},"doc://com.apple.documentation/documentation/technologies":{"abstract":[{"text":"","type":"text"}],"title":"Technologies","kind":"technologies","role":"overview","identifier":"doc://com.apple.documentation/documentation/technologies","type":"topic","url":"/documentation/technologies"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/height":{"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/height","type":"topic","navigatorTitle":[{"text":"MKMapRectGetHeight","kind":"identifier"}],"title":"height","abstract":[{"text":"Returns the height of the map rectangle.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"/documentation/mapkit/mkmaprect/height","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/null":{"url":"/documentation/mapkit/mkmaprect/null","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"null"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectNull"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/null","kind":"symbol","title":"null","role":"symbol","abstract":[{"type":"text","text":"The null map rectangle."}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midY":{"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midY","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MKMapRectGetMidY"}],"title":"midY","abstract":[{"text":"Returns the mid-point along the y-axis of the specified rectangle.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"midY"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"/documentation/mapkit/mkmaprect/midy","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersection(_:)":{"url":"/documentation/mapkit/mkmaprect/intersection(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intersection","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectIntersection"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersection(_:)","kind":"symbol","title":"intersection(_:)","role":"symbol","abstract":[{"type":"text","text":"Returns the rectangle that represents the intersection of two rectangles."}]},"doc://com.externally.resolved.symbol/s:s8SendableP":{"abstract":[{"text":"A thread-safe type whose values can be shared across arbitrary concurrent contexts without introducing a risk of data races.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sendable","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"SendableMetatype","kind":"typeIdentifier","preciseIdentifier":"s:s16SendableMetatypeP"}],"title":"Sendable","kind":"symbol","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s8SendableP","type":"topic","url":"/documentation/Swift/Sendable"},"doc://com.apple.mapkit/documentation/MapKit":{"role":"collection","kind":"symbol","type":"topic","title":"MapKit","abstract":[{"text":"Display map or satellite imagery within your app, call out points of interest, and determine placemark information for map coordinates.","type":"text"}],"url":"/documentation/mapkit","identifier":"doc://com.apple.mapkit/documentation/MapKit"},"doc://com.apple.mapkit/documentation/MapKit/MKMapSize":{"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapSize","abstract":[{"type":"text","text":"Width and height information on a two-dimensional map projection."}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MKMapSize","kind":"identifier"}],"title":"MKMapSize","role":"symbol","url":"/documentation/mapkit/mkmapsize","kind":"symbol","navigatorTitle":[{"text":"MKMapSize","kind":"identifier"}],"type":"topic"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/width":{"role":"symbol","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/width","type":"topic","navigatorTitle":[{"text":"MKMapRectGetWidth","kind":"identifier"}],"title":"width","abstract":[{"text":"Returns the width of the map rectangle.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"/documentation/mapkit/mkmaprect/width","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/insetBy(dx:dy:)":{"url":"/documentation/mapkit/mkmaprect/insetby(dx:dy:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"insetBy","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"dx"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dy"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@SA@MKMapRect","kind":"typeIdentifier","text":"MKMapRect"}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectInset"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/insetBy(dx:dy:)","kind":"symbol","title":"insetBy(dx:dy:)","role":"symbol","abstract":[{"type":"text","text":"Returns the specified rectangle with an inset by the specified amounts."}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxX":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxX","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"abstract":[{"type":"text","text":"Returns the maximum x-axis value of the specified rectangle."}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectGetMaxX"}],"title":"maxX","url":"/documentation/mapkit/mkmaprect/maxx","role":"symbol","type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxX","kind":"symbol"},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/origin":{"url":"/documentation/mapkit/mkmaprect/origin","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@SA@MKMapPoint","kind":"typeIdentifier","text":"MKMapPoint"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/origin","kind":"symbol","title":"origin","role":"symbol","abstract":[{"text":"The origin point of the rectangle.","type":"text"}]},"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midX":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"midX"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Returns the mid-point along the x-axis of the specified rectangle."}],"navigatorTitle":[{"kind":"identifier","text":"MKMapRectGetMidX"}],"title":"midX","url":"/documentation/mapkit/mkmaprect/midx","role":"symbol","type":"topic","identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midX","kind":"symbol"},"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP":{"kind":"symbol","abstract":[{"type":"text","text":""}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BitwiseCopyable","kind":"identifier"},{"text":" : ~Escapable","kind":"text"}],"type":"topic","title":"BitwiseCopyable","url":"/documentation/Swift/BitwiseCopyable","role":"symbol","identifier":"doc://com.externally.resolved.symbol/s:s15BitwiseCopyableP"},"doc://com.apple.mapkit/documentation/MapKit/MKMapPoint":{"kind":"symbol","navigatorTitle":[{"text":"MKMapPoint","kind":"identifier"}],"title":"MKMapPoint","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MKMapPoint"}],"role":"symbol","type":"topic","url":"/documentation/mapkit/mkmappoint","abstract":[{"type":"text","text":"A point on a two-dimensional map projection."}],"identifier":"doc://com.apple.mapkit/documentation/MapKit/MKMapPoint"}},"variantOverrides":[{"patch":[{"op":"replace","path":"/identifier/interfaceLanguage","value":"occ"},{"op":"replace","path":"/metadata/platforms","value":[{"name":"iOS","beta":false,"deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"deprecated":false,"unavailable":false},{"unavailable":false,"deprecated":false,"name":"tvOS","beta":false},{"unavailable":false,"deprecated":false,"name":"visionOS","beta":false},{"unavailable":false,"deprecated":false,"name":"watchOS","beta":false}]},{"op":"replace","path":"/metadata/roleHeading","value":"Structure"},{"op":"replace","path":"/metadata/title","value":"MKMapRect"},{"op":"replace","path":"/metadata/symbolKind","value":"struct"},{"op":"replace","path":"/metadata/fragments","value":[{"kind":"identifier","text":"MKMapRect"}]},{"op":"replace","path":"/metadata/navigatorTitle","value":[{"kind":"identifier","text":"MKMapRect"}]},{"op":"replace","path":"/hierarchy","value":{"paths":[["doc://com.apple.documentation/documentation/technologies","doc://com.apple.mapkit/documentation/MapKit"]]}},{"op":"replace","path":"/topicSections","value":[{"title":"Creating a map rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/init(x:y:width:height:)","doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion/init(_:)"],"anchor":"Creating-a-map-rectangle"},{"title":"Getting standard map rectangles","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/null","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/world"],"anchor":"Getting-standard-map-rectangles"},{"title":"Getting the rectangle coordinates","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/origin","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/size"],"anchor":"Getting-the-rectangle-coordinates"},{"title":"Getting the boundaries","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minX","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/minY","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midX","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/midY","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxX","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/maxY","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/width","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/height"],"anchor":"Getting-the-boundaries"},{"title":"Comparing rectangles","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isNull","doc://com.apple.mapkit/documentation/MapKit/MKMapRectEqualToRect(_:_:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/isEmpty","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/spans180thMeridian","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/remainder"],"anchor":"Comparing-rectangles"},{"title":"Intersecting the rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-79tjt","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/contains(_:)-1z5oa","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersects(_:)"],"anchor":"Intersecting-the-rectangle"},{"title":"Modifying the rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKMapRect/union(_:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/intersection(_:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/insetBy(dx:dy:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRect/offsetBy(dx:dy:)","doc://com.apple.mapkit/documentation/MapKit/MKMapRectDivide(_:_:_:_:_:)"],"anchor":"Modifying-the-rectangle"},{"title":"Getting a description of the rectangle","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKStringFromMapRect(_:)"],"anchor":"Getting-a-description-of-the-rectangle"}]},{"op":"replace","path":"/relationshipsSections","value":null},{"op":"replace","path":"/seeAlsoSections","value":[{"title":"Map coordinates","identifiers":["doc://com.apple.mapkit/documentation/MapKit/MKCoordinateRegion","doc://com.apple.mapkit/documentation/MapKit/MKCoordinateSpan","doc://com.apple.mapkit/documentation/MapKit/MKMapPoint","doc://com.apple.mapkit/documentation/MapKit/MKMapSize","doc://com.apple.mapkit/documentation/MapKit/MKDistanceFormatter"],"generated":true,"anchor":"Map-coordinates"}]},{"value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" { ... } ","kind":"text"},{"text":"MKMapRect","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS","iPadOS","Mac Catalyst","macOS","tvOS","visionOS","watchOS"]}],"kind":"declarations"},"path":"/primaryContentSections/0","op":"replace"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1spans180thMeridian/title","value":"MKMapRectSpans180thMeridian"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1spans180thMeridian/fragments","value":[{"text":"MKMapRectSpans180thMeridian","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1contains(_:)-1z5oa/title","value":"MKMapRectContainsRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1contains(_:)-1z5oa/fragments","value":[{"text":"MKMapRectContainsRect","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1contains(_:)-79tjt/title","value":"MKMapRectContainsPoint"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1contains(_:)-79tjt/fragments","value":[{"kind":"identifier","text":"MKMapRectContainsPoint"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1remainder/title","value":"MKMapRectRemainder"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1remainder/fragments","value":[{"text":"MKMapRectRemainder","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1minY/title","value":"MKMapRectGetMinY"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1minY/fragments","value":[{"kind":"identifier","text":"MKMapRectGetMinY"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1world/title","value":"MKMapRectWorld"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1world/fragments","value":[{"text":"MKMapRectWorld","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1intersects(_:)/title","value":"MKMapRectIntersectsRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1intersects(_:)/fragments","value":[{"text":"MKMapRectIntersectsRect","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRectDivide(_:_:_:_:_:)/title","value":"MKMapRectDivide"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRectDivide(_:_:_:_:_:)/fragments","value":[{"text":"MKMapRectDivide","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/title","value":"MKDistanceFormatter"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/fragments","value":[{"text":"MKDistanceFormatter","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKDistanceFormatter/navigatorTitle","value":[{"text":"MKDistanceFormatter","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1size/title","value":"size"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1size/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1init(x:y:width:height:)/title","value":"MKMapRectMake"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1init(x:y:width:height:)/fragments","value":[{"kind":"identifier","text":"MKMapRectMake"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStringFromMapRect(_:)/title","value":"MKStringFromMapRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKStringFromMapRect(_:)/fragments","value":[{"kind":"identifier","text":"MKStringFromMapRect"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/title","value":"MKMapRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/fragments","value":[{"kind":"identifier","text":"MKMapRect"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect/navigatorTitle","value":[{"text":"MKMapRect","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/title","value":"MKCoordinateRegion"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/fragments","value":[{"kind":"identifier","text":"MKCoordinateRegion"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion/navigatorTitle","value":[{"kind":"identifier","text":"MKCoordinateRegion"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1minX/title","value":"MKMapRectGetMinX"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1minX/fragments","value":[{"kind":"identifier","text":"MKMapRectGetMinX"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1isEmpty/title","value":"MKMapRectIsEmpty"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1isEmpty/fragments","value":[{"kind":"identifier","text":"MKMapRectIsEmpty"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion~1init(_:)/title","value":"MKCoordinateRegionForMapRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateRegion~1init(_:)/fragments","value":[{"text":"MKCoordinateRegionForMapRect","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/title","value":"MKCoordinateSpan"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/fragments","value":[{"kind":"identifier","text":"MKCoordinateSpan"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKCoordinateSpan/navigatorTitle","value":[{"text":"MKCoordinateSpan","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1union(_:)/title","value":"MKMapRectUnion"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1union(_:)/fragments","value":[{"kind":"identifier","text":"MKMapRectUnion"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1offsetBy(dx:dy:)/title","value":"MKMapRectOffset"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1offsetBy(dx:dy:)/fragments","value":[{"kind":"identifier","text":"MKMapRectOffset"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1isNull/title","value":"MKMapRectIsNull"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1isNull/fragments","value":[{"kind":"identifier","text":"MKMapRectIsNull"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRectEqualToRect(_:_:)/title","value":"MKMapRectEqualToRect"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRectEqualToRect(_:_:)/fragments","value":[{"text":"MKMapRectEqualToRect","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1maxY/title","value":"MKMapRectGetMaxY"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1maxY/fragments","value":[{"kind":"identifier","text":"MKMapRectGetMaxY"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1height/title","value":"MKMapRectGetHeight"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1height/fragments","value":[{"kind":"identifier","text":"MKMapRectGetHeight"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1null/title","value":"MKMapRectNull"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1null/fragments","value":[{"text":"MKMapRectNull","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1midY/title","value":"MKMapRectGetMidY"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1midY/fragments","value":[{"text":"MKMapRectGetMidY","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1intersection(_:)/title","value":"MKMapRectIntersection"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1intersection(_:)/fragments","value":[{"kind":"identifier","text":"MKMapRectIntersection"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/title","value":"MKMapSize"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/fragments","value":[{"text":"MKMapSize","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapSize/navigatorTitle","value":[{"text":"MKMapSize","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1width/title","value":"MKMapRectGetWidth"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1width/fragments","value":[{"text":"MKMapRectGetWidth","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1insetBy(dx:dy:)/title","value":"MKMapRectInset"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1insetBy(dx:dy:)/fragments","value":[{"text":"MKMapRectInset","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1maxX/title","value":"MKMapRectGetMaxX"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1maxX/fragments","value":[{"text":"MKMapRectGetMaxX","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1origin/title","value":"origin"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1origin/fragments","value":[{"text":"origin","kind":"identifier"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1midX/title","value":"MKMapRectGetMidX"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapRect~1midX/fragments","value":[{"kind":"identifier","text":"MKMapRectGetMidX"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/title","value":"MKMapPoint"},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/fragments","value":[{"kind":"identifier","text":"MKMapPoint"}]},{"op":"replace","path":"/references/doc:~1~1com.apple.mapkit~1documentation~1MapKit~1MKMapPoint/navigatorTitle","value":[{"text":"MKMapPoint","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}],"legalNotices":{"copyright":"Copyright &copy; 2025 Apple Inc. All rights reserved.","termsOfUse":"https://www.apple.com/legal/internet-services/terms/site.html","privacyPolicy":"https://www.apple.com/privacy/privacy-policy"}}